#include "blocktextures.h"

#include "../util.h"

#include <boost/filesystem.hpp>
#include <iostream>

namespace fs = boost::filesystem;

namespace mapcrafter {
namespace renderer {

BlockTextures::BlockTextures()
    : ACACIA_DOOR_BOTTOM("acacia_door_bottom"), ACACIA_DOOR_TOP("acacia_door_top"),
      ACACIA_LEAVES("acacia_leaves"), ACACIA_LOG("acacia_log"), ACACIA_LOG_TOP("acacia_log_top"),
      ACACIA_PLANKS("acacia_planks"), ACACIA_SAPLING("acacia_sapling"),
      ACACIA_TRAPDOOR("acacia_trapdoor"), ACTIVATOR_RAIL("activator_rail"),
      ACTIVATOR_RAIL_ON("activator_rail_on"), ALLIUM("allium"), AMETHYST_BLOCK("amethyst_block"),
      AMETHYST_CLUSTER("amethyst_cluster"), ANCIENT_DEBRIS_SIDE("ancient_debris_side"),
      ANCIENT_DEBRIS_TOP("ancient_debris_top"), ANDESITE("andesite"), ANVIL("anvil"),
      ANVIL_TOP("anvil_top"), ATTACHED_MELON_STEM("attached_melon_stem"),
      ATTACHED_PUMPKIN_STEM("attached_pumpkin_stem"), AZALEA_LEAVES("azalea_leaves"),
      AZALEA_PLANT("azalea_plant"), AZALEA_SIDE("azalea_side"), AZALEA_TOP("azalea_top"),
      AZURE_BLUET("azure_bluet"), BAMBOO_LARGE_LEAVES("bamboo_large_leaves"),
      BAMBOO_SINGLELEAF("bamboo_singleleaf"), BAMBOO_SMALL_LEAVES("bamboo_small_leaves"),
      BAMBOO_STAGE0("bamboo_stage0"), BAMBOO_STALK("bamboo_stalk"), BARREL_BOTTOM("barrel_bottom"),
      BARREL_SIDE("barrel_side"), BARREL_TOP("barrel_top"), BARREL_TOP_OPEN("barrel_top_open"),
      BASALT_SIDE("basalt_side"), BASALT_TOP("basalt_top"), BEACON("beacon"), BEDROCK("bedrock"),
      BEE_NEST_BOTTOM("bee_nest_bottom"), BEE_NEST_FRONT("bee_nest_front"),
      BEE_NEST_FRONT_HONEY("bee_nest_front_honey"), BEE_NEST_SIDE("bee_nest_side"),
      BEE_NEST_TOP("bee_nest_top"), BEEHIVE_END("beehive_end"), BEEHIVE_FRONT("beehive_front"),
      BEEHIVE_FRONT_HONEY("beehive_front_honey"), BEEHIVE_SIDE("beehive_side"),
      BEETROOTS_STAGE0("beetroots_stage0"), BEETROOTS_STAGE1("beetroots_stage1"),
      BEETROOTS_STAGE2("beetroots_stage2"), BEETROOTS_STAGE3("beetroots_stage3"),
      BELL_BOTTOM("bell_bottom"), BELL_SIDE("bell_side"), BELL_TOP("bell_top"),
      BIG_DRIPLEAF_SIDE("big_dripleaf_side"), BIG_DRIPLEAF_STEM("big_dripleaf_stem"),
      BIG_DRIPLEAF_TIP("big_dripleaf_tip"), BIG_DRIPLEAF_TOP("big_dripleaf_top"),
      BIRCH_DOOR_BOTTOM("birch_door_bottom"), BIRCH_DOOR_TOP("birch_door_top"),
      BIRCH_LEAVES("birch_leaves"), BIRCH_LOG("birch_log"), BIRCH_LOG_TOP("birch_log_top"),
      BIRCH_PLANKS("birch_planks"), BIRCH_SAPLING("birch_sapling"),
      BIRCH_TRAPDOOR("birch_trapdoor"), BLACK_CANDLE("black_candle"),
      BLACK_CANDLE_LIT("black_candle_lit"), BLACK_CONCRETE("black_concrete"),
      BLACK_CONCRETE_POWDER("black_concrete_powder"),
      BLACK_GLAZED_TERRACOTTA("black_glazed_terracotta"), BLACK_SHULKER_BOX("black_shulker_box"),
      BLACK_STAINED_GLASS("black_stained_glass"),
      BLACK_STAINED_GLASS_PANE_TOP("black_stained_glass_pane_top"),
      BLACK_TERRACOTTA("black_terracotta"), BLACK_WOOL("black_wool"), BLACKSTONE("blackstone"),
      BLACKSTONE_TOP("blackstone_top"), BLAST_FURNACE_FRONT("blast_furnace_front"),
      BLAST_FURNACE_FRONT_ON("blast_furnace_front_on"), BLAST_FURNACE_SIDE("blast_furnace_side"),
      BLAST_FURNACE_TOP("blast_furnace_top"), BLUE_CANDLE("blue_candle"),
      BLUE_CANDLE_LIT("blue_candle_lit"), BLUE_CONCRETE("blue_concrete"),
      BLUE_CONCRETE_POWDER("blue_concrete_powder"),
      BLUE_GLAZED_TERRACOTTA("blue_glazed_terracotta"), BLUE_ICE("blue_ice"),
      BLUE_ORCHID("blue_orchid"), BLUE_SHULKER_BOX("blue_shulker_box"),
      BLUE_STAINED_GLASS("blue_stained_glass"),
      BLUE_STAINED_GLASS_PANE_TOP("blue_stained_glass_pane_top"),
      BLUE_TERRACOTTA("blue_terracotta"), BLUE_WOOL("blue_wool"),
      BONE_BLOCK_SIDE("bone_block_side"), BONE_BLOCK_TOP("bone_block_top"), BOOKSHELF("bookshelf"),
      BRAIN_CORAL("brain_coral"), BRAIN_CORAL_BLOCK("brain_coral_block"),
      BRAIN_CORAL_FAN("brain_coral_fan"), BREWING_STAND("brewing_stand"),
      BREWING_STAND_BASE("brewing_stand_base"), BRICKS("bricks"), BROWN_CANDLE("brown_candle"),
      BROWN_CANDLE_LIT("brown_candle_lit"), BROWN_CONCRETE("brown_concrete"),
      BROWN_CONCRETE_POWDER("brown_concrete_powder"),
      BROWN_GLAZED_TERRACOTTA("brown_glazed_terracotta"), BROWN_MUSHROOM("brown_mushroom"),
      BROWN_MUSHROOM_BLOCK("brown_mushroom_block"), BROWN_SHULKER_BOX("brown_shulker_box"),
      BROWN_STAINED_GLASS("brown_stained_glass"),
      BROWN_STAINED_GLASS_PANE_TOP("brown_stained_glass_pane_top"),
      BROWN_TERRACOTTA("brown_terracotta"), BROWN_WOOL("brown_wool"), BUBBLE_CORAL("bubble_coral"),
      BUBBLE_CORAL_BLOCK("bubble_coral_block"), BUBBLE_CORAL_FAN("bubble_coral_fan"),
      BUDDING_AMETHYST("budding_amethyst"), CACTUS_BOTTOM("cactus_bottom"),
      CACTUS_SIDE("cactus_side"), CACTUS_TOP("cactus_top"), CAKE_BOTTOM("cake_bottom"),
      CAKE_INNER("cake_inner"), CAKE_SIDE("cake_side"), CAKE_TOP("cake_top"), CALCITE("calcite"),
      CAMPFIRE_FIRE("campfire_fire"), CAMPFIRE_LOG("campfire_log"),
      CAMPFIRE_LOG_LIT("campfire_log_lit"), CANDLE("candle"), CANDLE_LIT("candle_lit"),
      CARROTS_STAGE0("carrots_stage0"), CARROTS_STAGE1("carrots_stage1"),
      CARROTS_STAGE2("carrots_stage2"), CARROTS_STAGE3("carrots_stage3"),
      CARTOGRAPHY_TABLE_SIDE1("cartography_table_side1"),
      CARTOGRAPHY_TABLE_SIDE2("cartography_table_side2"),
      CARTOGRAPHY_TABLE_SIDE3("cartography_table_side3"),
      CARTOGRAPHY_TABLE_TOP("cartography_table_top"), CARVED_PUMPKIN("carved_pumpkin"),
      CAULDRON_BOTTOM("cauldron_bottom"), CAULDRON_INNER("cauldron_inner"),
      CAULDRON_SIDE("cauldron_side"), CAULDRON_TOP("cauldron_top"), CAVE_VINES("cave_vines"),
      CAVE_VINES_LIT("cave_vines_lit"), CAVE_VINES_PLANT("cave_vines_plant"),
      CAVE_VINES_PLANT_LIT("cave_vines_plant_lit"), CHAIN("chain"),
      CHAIN_COMMAND_BLOCK_BACK("chain_command_block_back"),
      CHAIN_COMMAND_BLOCK_CONDITIONAL("chain_command_block_conditional"),
      CHAIN_COMMAND_BLOCK_FRONT("chain_command_block_front"),
      CHAIN_COMMAND_BLOCK_SIDE("chain_command_block_side"), CHIPPED_ANVIL_TOP("chipped_anvil_top"),
      CHISELED_DEEPSLATE("chiseled_deepslate"), CHISELED_NETHER_BRICKS("chiseled_nether_bricks"),
      CHISELED_POLISHED_BLACKSTONE("chiseled_polished_blackstone"),
      CHISELED_QUARTZ_BLOCK("chiseled_quartz_block"),
      CHISELED_QUARTZ_BLOCK_TOP("chiseled_quartz_block_top"),
      CHISELED_RED_SANDSTONE("chiseled_red_sandstone"), CHISELED_SANDSTONE("chiseled_sandstone"),
      CHISELED_STONE_BRICKS("chiseled_stone_bricks"), CHORUS_FLOWER("chorus_flower"),
      CHORUS_FLOWER_DEAD("chorus_flower_dead"), CHORUS_PLANT("chorus_plant"), CLAY("clay"),
      COAL_BLOCK("coal_block"), COAL_ORE("coal_ore"), COARSE_DIRT("coarse_dirt"),
      COBBLED_DEEPSLATE("cobbled_deepslate"), COBBLESTONE("cobblestone"), COBWEB("cobweb"),
      COCOA_STAGE0("cocoa_stage0"), COCOA_STAGE1("cocoa_stage1"), COCOA_STAGE2("cocoa_stage2"),
      COMMAND_BLOCK_BACK("command_block_back"),
      COMMAND_BLOCK_CONDITIONAL("command_block_conditional"),
      COMMAND_BLOCK_FRONT("command_block_front"), COMMAND_BLOCK_SIDE("command_block_side"),
      COMPARATOR("comparator"), COMPARATOR_ON("comparator_on"),
      COMPOSTER_BOTTOM("composter_bottom"), COMPOSTER_COMPOST("composter_compost"),
      COMPOSTER_READY("composter_ready"), COMPOSTER_SIDE("composter_side"),
      COMPOSTER_TOP("composter_top"), CONDUIT("conduit"), COPPER_BLOCK("copper_block"),
      COPPER_ORE("copper_ore"), CORNFLOWER("cornflower"),
      CRACKED_DEEPSLATE_BRICKS("cracked_deepslate_bricks"),
      CRACKED_DEEPSLATE_TILES("cracked_deepslate_tiles"),
      CRACKED_NETHER_BRICKS("cracked_nether_bricks"),
      CRACKED_POLISHED_BLACKSTONE_BRICKS("cracked_polished_blackstone_bricks"),
      CRACKED_STONE_BRICKS("cracked_stone_bricks"), CRAFTING_TABLE_FRONT("crafting_table_front"),
      CRAFTING_TABLE_SIDE("crafting_table_side"), CRAFTING_TABLE_TOP("crafting_table_top"),
      CRIMSON_DOOR_BOTTOM("crimson_door_bottom"), CRIMSON_DOOR_TOP("crimson_door_top"),
      CRIMSON_FUNGUS("crimson_fungus"), CRIMSON_NYLIUM("crimson_nylium"),
      CRIMSON_NYLIUM_SIDE("crimson_nylium_side"), CRIMSON_PLANKS("crimson_planks"),
      CRIMSON_ROOTS("crimson_roots"), CRIMSON_ROOTS_POT("crimson_roots_pot"),
      CRIMSON_STEM("crimson_stem"), CRIMSON_STEM_TOP("crimson_stem_top"),
      CRIMSON_TRAPDOOR("crimson_trapdoor"), CRYING_OBSIDIAN("crying_obsidian"),
      CUT_COPPER("cut_copper"), CUT_RED_SANDSTONE("cut_red_sandstone"),
      CUT_SANDSTONE("cut_sandstone"), CYAN_CANDLE("cyan_candle"),
      CYAN_CANDLE_LIT("cyan_candle_lit"), CYAN_CONCRETE("cyan_concrete"),
      CYAN_CONCRETE_POWDER("cyan_concrete_powder"),
      CYAN_GLAZED_TERRACOTTA("cyan_glazed_terracotta"), CYAN_SHULKER_BOX("cyan_shulker_box"),
      CYAN_STAINED_GLASS("cyan_stained_glass"),
      CYAN_STAINED_GLASS_PANE_TOP("cyan_stained_glass_pane_top"),
      CYAN_TERRACOTTA("cyan_terracotta"), CYAN_WOOL("cyan_wool"),
      DAMAGED_ANVIL_TOP("damaged_anvil_top"), DANDELION("dandelion"),
      DARK_OAK_DOOR_BOTTOM("dark_oak_door_bottom"), DARK_OAK_DOOR_TOP("dark_oak_door_top"),
      DARK_OAK_LEAVES("dark_oak_leaves"), DARK_OAK_LOG("dark_oak_log"),
      DARK_OAK_LOG_TOP("dark_oak_log_top"), DARK_OAK_PLANKS("dark_oak_planks"),
      DARK_OAK_SAPLING("dark_oak_sapling"), DARK_OAK_TRAPDOOR("dark_oak_trapdoor"),
      DARK_PRISMARINE("dark_prismarine"),
      DAYLIGHT_DETECTOR_INVERTED_TOP("daylight_detector_inverted_top"),
      DAYLIGHT_DETECTOR_SIDE("daylight_detector_side"),
      DAYLIGHT_DETECTOR_TOP("daylight_detector_top"), DEAD_BRAIN_CORAL("dead_brain_coral"),
      DEAD_BRAIN_CORAL_BLOCK("dead_brain_coral_block"),
      DEAD_BRAIN_CORAL_FAN("dead_brain_coral_fan"), DEAD_BUBBLE_CORAL("dead_bubble_coral"),
      DEAD_BUBBLE_CORAL_BLOCK("dead_bubble_coral_block"),
      DEAD_BUBBLE_CORAL_FAN("dead_bubble_coral_fan"), DEAD_BUSH("dead_bush"),
      DEAD_FIRE_CORAL("dead_fire_coral"), DEAD_FIRE_CORAL_BLOCK("dead_fire_coral_block"),
      DEAD_FIRE_CORAL_FAN("dead_fire_coral_fan"), DEAD_HORN_CORAL("dead_horn_coral"),
      DEAD_HORN_CORAL_BLOCK("dead_horn_coral_block"), DEAD_HORN_CORAL_FAN("dead_horn_coral_fan"),
      DEAD_TUBE_CORAL("dead_tube_coral"), DEAD_TUBE_CORAL_BLOCK("dead_tube_coral_block"),
      DEAD_TUBE_CORAL_FAN("dead_tube_coral_fan"), DEBUG("debug"), DEBUG2("debug2"),
      DEEPSLATE("deepslate"), DEEPSLATE_BRICKS("deepslate_bricks"),
      DEEPSLATE_COAL_ORE("deepslate_coal_ore"), DEEPSLATE_COPPER_ORE("deepslate_copper_ore"),
      DEEPSLATE_DIAMOND_ORE("deepslate_diamond_ore"),
      DEEPSLATE_EMERALD_ORE("deepslate_emerald_ore"), DEEPSLATE_GOLD_ORE("deepslate_gold_ore"),
      DEEPSLATE_IRON_ORE("deepslate_iron_ore"), DEEPSLATE_LAPIS_ORE("deepslate_lapis_ore"),
      DEEPSLATE_REDSTONE_ORE("deepslate_redstone_ore"), DEEPSLATE_TILES("deepslate_tiles"),
      DEEPSLATE_TOP("deepslate_top"), DESTROY_STAGE_0("destroy_stage_0"),
      DESTROY_STAGE_1("destroy_stage_1"), DESTROY_STAGE_2("destroy_stage_2"),
      DESTROY_STAGE_3("destroy_stage_3"), DESTROY_STAGE_4("destroy_stage_4"),
      DESTROY_STAGE_5("destroy_stage_5"), DESTROY_STAGE_6("destroy_stage_6"),
      DESTROY_STAGE_7("destroy_stage_7"), DESTROY_STAGE_8("destroy_stage_8"),
      DESTROY_STAGE_9("destroy_stage_9"), DETECTOR_RAIL("detector_rail"),
      DETECTOR_RAIL_ON("detector_rail_on"), DIAMOND_BLOCK("diamond_block"),
      DIAMOND_ORE("diamond_ore"), DIORITE("diorite"), DIRT("dirt"),
      DIRT_PATH_SIDE("dirt_path_side"), DIRT_PATH_TOP("dirt_path_top"),
      DISPENSER_FRONT("dispenser_front"), DISPENSER_FRONT_VERTICAL("dispenser_front_vertical"),
      DRAGON_EGG("dragon_egg"), DRIED_KELP_BOTTOM("dried_kelp_bottom"),
      DRIED_KELP_SIDE("dried_kelp_side"), DRIED_KELP_TOP("dried_kelp_top"),
      DRIPSTONE_BLOCK("dripstone_block"), DROPPER_FRONT("dropper_front"),
	  CHAIN_COMMAND_BLOCK_BACK("chain_command_block_back"),
	  CHAIN_COMMAND_BLOCK_CONDITIONAL("chain_command_block_conditional"),
	  CHAIN_COMMAND_BLOCK_FRONT("chain_command_block_front"),
	  CHAIN_COMMAND_BLOCK_SIDE("chain_command_block_side"),
      END_PORTAL_FRAME_TOP("end_portal_frame_top"), END_ROD("end_rod"), END_STONE("end_stone"),
      END_STONE_BRICKS("end_stone_bricks"), EXPOSED_COPPER("exposed_copper"),
      EXPOSED_CUT_COPPER("exposed_cut_copper"), FARMLAND("farmland"),
      FARMLAND_MOIST("farmland_moist"), FERN("fern"), FIRE_0("fire_0"), FIRE_1("fire_1"),
      FIRE_CORAL("fire_coral"), FIRE_CORAL_BLOCK("fire_coral_block"),
      FIRE_CORAL_FAN("fire_coral_fan"), FLETCHING_TABLE_FRONT("fletching_table_front"),
      FLETCHING_TABLE_SIDE("fletching_table_side"), FLETCHING_TABLE_TOP("fletching_table_top"),
      FLOWER_POT("flower_pot"), FLOWERING_AZALEA_LEAVES("flowering_azalea_leaves"),
      FLOWERING_AZALEA_SIDE("flowering_azalea_side"), FLOWERING_AZALEA_TOP("flowering_azalea_top"),
	  CHORUS_FLOWER("chorus_flower"),
	  CHORUS_FLOWER_DEAD("chorus_flower_dead"),
	  CHORUS_PLANT("chorus_plant"),
      FURNACE_SIDE("furnace_side"), FURNACE_TOP("furnace_top"),
      GILDED_BLACKSTONE("gilded_blackstone"), GLASS("glass"), GLASS_PANE_TOP("glass_pane_top"),
      GLOW_ITEM_FRAME("glow_item_frame"), GLOW_LICHEN("glow_lichen"), GLOWSTONE("glowstone"),
	  COARSE_DIRT("coarse_dirt"),
      GRASS_BLOCK_SIDE("grass_block_side"), GRASS_BLOCK_SIDE_OVERLAY("grass_block_side_overlay"),
      GRASS_BLOCK_SNOW("grass_block_snow"), GRASS_BLOCK_TOP("grass_block_top"),
      GRASS_PATH_SIDE("grass_path_side"), GRASS_PATH_TOP("grass_path_top"), GRAVEL("gravel"),
      GRAY_CANDLE("gray_candle"), GRAY_CANDLE_LIT("gray_candle_lit"),
      GRAY_CONCRETE("gray_concrete"), GRAY_CONCRETE_POWDER("gray_concrete_powder"),
      GRAY_GLAZED_TERRACOTTA("gray_glazed_terracotta"), GRAY_SHULKER_BOX("gray_shulker_box"),
	  COMMAND_BLOCK_BACK("command_block_back"),
	  COMMAND_BLOCK_CONDITIONAL("command_block_conditional"),
	  COMMAND_BLOCK_FRONT("command_block_front"),
	  COMMAND_BLOCK_SIDE("command_block_side"),
      GREEN_CONCRETE_POWDER("green_concrete_powder"),
      GREEN_GLAZED_TERRACOTTA("green_glazed_terracotta"), GREEN_SHULKER_BOX("green_shulker_box"),
      GREEN_STAINED_GLASS("green_stained_glass"),
      GREEN_STAINED_GLASS_PANE_TOP("green_stained_glass_pane_top"),
      GREEN_TERRACOTTA("green_terracotta"), GREEN_WOOL("green_wool"),
      GRINDSTONE_PIVOT("grindstone_pivot"), GRINDSTONE_ROUND("grindstone_round"),
      GRINDSTONE_SIDE("grindstone_side"), HANGING_ROOTS("hanging_roots"),
      HAY_BLOCK_SIDE("hay_block_side"), HAY_BLOCK_TOP("hay_block_top"),
      HONEY_BLOCK_BOTTOM("honey_block_bottom"), HONEY_BLOCK_SIDE("honey_block_side"),
      HONEY_BLOCK_TOP("honey_block_top"), HONEYCOMB_BLOCK("honeycomb_block"),
      HOPPER_INSIDE("hopper_inside"), HOPPER_OUTSIDE("hopper_outside"), HOPPER_TOP("hopper_top"),
      HORN_CORAL("horn_coral"), HORN_CORAL_BLOCK("horn_coral_block"),
      HORN_CORAL_FAN("horn_coral_fan"), ICE("ice"), IRON_BARS("iron_bars"),
      IRON_BLOCK("iron_block"), IRON_DOOR_BOTTOM("iron_door_bottom"),
      IRON_DOOR_TOP("iron_door_top"), IRON_ORE("iron_ore"), IRON_TRAPDOOR("iron_trapdoor"),
      ITEM_FRAME("item_frame"), JACK_O_LANTERN("jack_o_lantern"), JIGSAW_BOTTOM("jigsaw_bottom"),
      JIGSAW_LOCK("jigsaw_lock"), JIGSAW_SIDE("jigsaw_side"), JIGSAW_TOP("jigsaw_top"),
      JUKEBOX_SIDE("jukebox_side"), JUKEBOX_TOP("jukebox_top"),
      JUNGLE_DOOR_BOTTOM("jungle_door_bottom"), JUNGLE_DOOR_TOP("jungle_door_top"),
      JUNGLE_LEAVES("jungle_leaves"), JUNGLE_LOG("jungle_log"), JUNGLE_LOG_TOP("jungle_log_top"),
      JUNGLE_PLANKS("jungle_planks"), JUNGLE_SAPLING("jungle_sapling"),
      JUNGLE_TRAPDOOR("jungle_trapdoor"), KELP("kelp"), KELP_PLANT("kelp_plant"), LADDER("ladder"),
      LANTERN("lantern"), LAPIS_BLOCK("lapis_block"), LAPIS_ORE("lapis_ore"),
      LARGE_AMETHYST_BUD("large_amethyst_bud"), LARGE_FERN_BOTTOM("large_fern_bottom"),
      LARGE_FERN_TOP("large_fern_top"), LAVA_FLOW("lava_flow"), LAVA_STILL("lava_still"),
      LECTERN_BASE("lectern_base"), LECTERN_FRONT("lectern_front"), LECTERN_SIDES("lectern_sides"),
      LECTERN_TOP("lectern_top"), LEVER("lever"), LIGHT_BLUE_CANDLE("light_blue_candle"),
      LIGHT_BLUE_CANDLE_LIT("light_blue_candle_lit"), LIGHT_BLUE_CONCRETE("light_blue_concrete"),
      LIGHT_BLUE_CONCRETE_POWDER("light_blue_concrete_powder"),
      LIGHT_BLUE_GLAZED_TERRACOTTA("light_blue_glazed_terracotta"),
      LIGHT_BLUE_SHULKER_BOX("light_blue_shulker_box"),
      LIGHT_BLUE_STAINED_GLASS("light_blue_stained_glass"),
      LIGHT_BLUE_STAINED_GLASS_PANE_TOP("light_blue_stained_glass_pane_top"),
      LIGHT_BLUE_TERRACOTTA("light_blue_terracotta"), LIGHT_BLUE_WOOL("light_blue_wool"),
      LIGHT_GRAY_CANDLE("light_gray_candle"), LIGHT_GRAY_CANDLE_LIT("light_gray_candle_lit"),
      LIGHT_GRAY_CONCRETE("light_gray_concrete"),
      LIGHT_GRAY_CONCRETE_POWDER("light_gray_concrete_powder"),
      LIGHT_GRAY_GLAZED_TERRACOTTA("light_gray_glazed_terracotta"),
      LIGHT_GRAY_SHULKER_BOX("light_gray_shulker_box"),
      LIGHT_GRAY_STAINED_GLASS("light_gray_stained_glass"),
      LIGHT_GRAY_STAINED_GLASS_PANE_TOP("light_gray_stained_glass_pane_top"),
      LIGHT_GRAY_TERRACOTTA("light_gray_terracotta"), LIGHT_GRAY_WOOL("light_gray_wool"),
      LIGHTNING_ROD("lightning_rod"), LIGHTNING_ROD_ON("lightning_rod_on"),
      LILAC_BOTTOM("lilac_bottom"), LILAC_TOP("lilac_top"),
      LILY_OF_THE_VALLEY("lily_of_the_valley"), LILY_PAD("lily_pad"), LIME_CANDLE("lime_candle"),
      LIME_CANDLE_LIT("lime_candle_lit"), LIME_CONCRETE("lime_concrete"),
      LIME_CONCRETE_POWDER("lime_concrete_powder"),
      LIME_GLAZED_TERRACOTTA("lime_glazed_terracotta"), LIME_SHULKER_BOX("lime_shulker_box"),
      LIME_STAINED_GLASS("lime_stained_glass"),
      LIME_STAINED_GLASS_PANE_TOP("lime_stained_glass_pane_top"),
      LIME_TERRACOTTA("lime_terracotta"), LIME_WOOL("lime_wool"), LODESTONE_SIDE("lodestone_side"),
      LODESTONE_TOP("lodestone_top"), LOOM_BOTTOM("loom_bottom"), LOOM_FRONT("loom_front"),
      LOOM_SIDE("loom_side"), LOOM_TOP("loom_top"), MAGENTA_CANDLE("magenta_candle"),
      MAGENTA_CANDLE_LIT("magenta_candle_lit"), MAGENTA_CONCRETE("magenta_concrete"),
      MAGENTA_CONCRETE_POWDER("magenta_concrete_powder"),
	  DAYLIGHT_DETECTOR_INVERTED_TOP("daylight_detector_inverted_top"),
      MAGENTA_SHULKER_BOX("magenta_shulker_box"), MAGENTA_STAINED_GLASS("magenta_stained_glass"),
      MAGENTA_STAINED_GLASS_PANE_TOP("magenta_stained_glass_pane_top"),
      MAGENTA_TERRACOTTA("magenta_terracotta"), MAGENTA_WOOL("magenta_wool"), MAGMA("magma"),
      MANGROVE_DOOR_BOTTOM("mangrove_door_bottom"), MANGROVE_DOOR_TOP("mangrove_door_top"),
      MANGROVE_LEAVES("mangrove_leaves"), MANGROVE_LOG("mangrove_log"),
      MANGROVE_LOG_TOP("mangrove_log_top"), MANGROVE_PLANKS("mangrove_planks"),
      MANGROVE_PROPAGULE("mangrove_propagule"),
      MANGROVE_PROPAGULE_HANGING("mangrove_propagule_hanging"),
      MANGROVE_ROOTS_SIDE("mangrove_roots_side"), MANGROVE_ROOTS_TOP("mangrove_roots_top"),
      MANGROVE_TRAPDOOR("mangrove_trapdoor"), MEDIUM_AMETHYST_BUD("medium_amethyst_bud"),
      MELON_SIDE("melon_side"), MELON_STEM("melon_stem"), MELON_TOP("melon_top"),
      MOSS_BLOCK("moss_block"), MOSSY_COBBLESTONE("mossy_cobblestone"),
      MOSSY_STONE_BRICKS("mossy_stone_bricks"), MUD("mud"), MUD_BRICKS("mud_bricks"),
      MUDDY_MANGROVE_ROOTS_SIDE("muddy_mangrove_roots_side"),
      MUDDY_MANGROVE_ROOTS_TOP("muddy_mangrove_roots_top"),
      MUSHROOM_BLOCK_INSIDE("mushroom_block_inside"), MUSHROOM_STEM("mushroom_stem"),
      MYCELIUM_SIDE("mycelium_side"), MYCELIUM_TOP("mycelium_top"), NETHER_BRICKS("nether_bricks"),
      NETHER_GOLD_ORE("nether_gold_ore"), NETHER_PORTAL("nether_portal"),
	  DEBUG("debug"),
	  DEBUG2("debug2"),
      NETHER_WART_STAGE1("nether_wart_stage1"), NETHER_WART_STAGE2("nether_wart_stage2"),
      NETHERITE_BLOCK("netherite_block"), NETHERRACK("netherrack"), NOTE_BLOCK("note_block"),
      OAK_DOOR_BOTTOM("oak_door_bottom"), OAK_DOOR_TOP("oak_door_top"), OAK_LEAVES("oak_leaves"),
      OAK_LOG("oak_log"), OAK_LOG_TOP("oak_log_top"), OAK_PLANKS("oak_planks"),
      OAK_SAPLING("oak_sapling"), OAK_TRAPDOOR("oak_trapdoor"), OBSERVER_BACK("observer_back"),
      OBSERVER_BACK_ON("observer_back_on"), OBSERVER_FRONT("observer_front"),
      OBSERVER_SIDE("observer_side"), OBSERVER_TOP("observer_top"), OBSIDIAN("obsidian"),
      OCHRE_FROGLIGHT_SIDE("ochre_froglight_side"), OCHRE_FROGLIGHT_TOP("ochre_froglight_top"),
      ORANGE_CANDLE("orange_candle"), ORANGE_CANDLE_LIT("orange_candle_lit"),
      ORANGE_CONCRETE("orange_concrete"), ORANGE_CONCRETE_POWDER("orange_concrete_powder"),
      ORANGE_GLAZED_TERRACOTTA("orange_glazed_terracotta"),
      ORANGE_SHULKER_BOX("orange_shulker_box"), ORANGE_STAINED_GLASS("orange_stained_glass"),
      ORANGE_STAINED_GLASS_PANE_TOP("orange_stained_glass_pane_top"),
      ORANGE_TERRACOTTA("orange_terracotta"), ORANGE_TULIP("orange_tulip"),
      ORANGE_WOOL("orange_wool"), OXEYE_DAISY("oxeye_daisy"), OXIDIZED_COPPER("oxidized_copper"),
      OXIDIZED_CUT_COPPER("oxidized_cut_copper"), PACKED_ICE("packed_ice"),
      PACKED_MUD("packed_mud"), PEARLESCENT_FROGLIGHT_SIDE("pearlescent_froglight_side"),
      PEARLESCENT_FROGLIGHT_TOP("pearlescent_froglight_top"), PEONY_BOTTOM("peony_bottom"),
      PEONY_TOP("peony_top"), PINK_CANDLE("pink_candle"), PINK_CANDLE_LIT("pink_candle_lit"),
      PINK_CONCRETE("pink_concrete"), PINK_CONCRETE_POWDER("pink_concrete_powder"),
      PINK_GLAZED_TERRACOTTA("pink_glazed_terracotta"), PINK_SHULKER_BOX("pink_shulker_box"),
      PINK_STAINED_GLASS("pink_stained_glass"),
      PINK_STAINED_GLASS_PANE_TOP("pink_stained_glass_pane_top"),
      PINK_TERRACOTTA("pink_terracotta"), PINK_TULIP("pink_tulip"), PINK_WOOL("pink_wool"),
      PISTON_BOTTOM("piston_bottom"), PISTON_INNER("piston_inner"), PISTON_SIDE("piston_side"),
      PISTON_TOP("piston_top"), PISTON_TOP_STICKY("piston_top_sticky"), PODZOL_SIDE("podzol_side"),
      PODZOL_TOP("podzol_top"), POINTED_DRIPSTONE_DOWN_BASE("pointed_dripstone_down_base"),
      POINTED_DRIPSTONE_DOWN_FRUSTUM("pointed_dripstone_down_frustum"),
      POINTED_DRIPSTONE_DOWN_MIDDLE("pointed_dripstone_down_middle"),
      POINTED_DRIPSTONE_DOWN_TIP("pointed_dripstone_down_tip"),
      POINTED_DRIPSTONE_DOWN_TIP_MERGE("pointed_dripstone_down_tip_merge"),
      POINTED_DRIPSTONE_UP_BASE("pointed_dripstone_up_base"),
      POINTED_DRIPSTONE_UP_FRUSTUM("pointed_dripstone_up_frustum"),
      POINTED_DRIPSTONE_UP_MIDDLE("pointed_dripstone_up_middle"),
      POINTED_DRIPSTONE_UP_TIP("pointed_dripstone_up_tip"),
      POINTED_DRIPSTONE_UP_TIP_MERGE("pointed_dripstone_up_tip_merge"),
      POLISHED_ANDESITE("polished_andesite"), POLISHED_BASALT_SIDE("polished_basalt_side"),
      POLISHED_BASALT_TOP("polished_basalt_top"), POLISHED_BLACKSTONE("polished_blackstone"),
      POLISHED_BLACKSTONE_BRICKS("polished_blackstone_bricks"),
      POLISHED_DEEPSLATE("polished_deepslate"), POLISHED_DIORITE("polished_diorite"),
      POLISHED_GRANITE("polished_granite"), POPPY("poppy"), POTATOES_STAGE0("potatoes_stage0"),
      POTATOES_STAGE1("potatoes_stage1"), POTATOES_STAGE2("potatoes_stage2"),
      POTATOES_STAGE3("potatoes_stage3"), POTTED_AZALEA_BUSH_PLANT("potted_azalea_bush_plant"),
      POTTED_AZALEA_BUSH_SIDE("potted_azalea_bush_side"),
      POTTED_AZALEA_BUSH_TOP("potted_azalea_bush_top"),
      POTTED_FLOWERING_AZALEA_BUSH_PLANT("potted_flowering_azalea_bush_plant"),
      POTTED_FLOWERING_AZALEA_BUSH_SIDE("potted_flowering_azalea_bush_side"),
	  END_ROD("end_rod"),
      POWDER_SNOW("powder_snow"), POWERED_RAIL("powered_rail"), POWERED_RAIL_ON("powered_rail_on"),
      PRISMARINE("prismarine"), PRISMARINE_BRICKS("prismarine_bricks"),
      PUMPKIN_SIDE("pumpkin_side"), PUMPKIN_STEM("pumpkin_stem"), PUMPKIN_TOP("pumpkin_top"),
      PURPLE_CANDLE("purple_candle"), PURPLE_CANDLE_LIT("purple_candle_lit"),
      PURPLE_CONCRETE("purple_concrete"), PURPLE_CONCRETE_POWDER("purple_concrete_powder"),
      PURPLE_GLAZED_TERRACOTTA("purple_glazed_terracotta"),
      PURPLE_SHULKER_BOX("purple_shulker_box"), PURPLE_STAINED_GLASS("purple_stained_glass"),
      PURPLE_STAINED_GLASS_PANE_TOP("purple_stained_glass_pane_top"),
      PURPLE_TERRACOTTA("purple_terracotta"), PURPLE_WOOL("purple_wool"),
      PURPUR_BLOCK("purpur_block"), PURPUR_PILLAR("purpur_pillar"),
      PURPUR_PILLAR_TOP("purpur_pillar_top"), QUARTZ_BLOCK_BOTTOM("quartz_block_bottom"),
      QUARTZ_BLOCK_SIDE("quartz_block_side"), QUARTZ_BLOCK_TOP("quartz_block_top"),
      QUARTZ_BRICKS("quartz_bricks"), QUARTZ_PILLAR("quartz_pillar"),
      QUARTZ_PILLAR_TOP("quartz_pillar_top"), RAIL("rail"), RAIL_CORNER("rail_corner"),
      RAW_COPPER_BLOCK("raw_copper_block"), RAW_GOLD_BLOCK("raw_gold_block"),
      RAW_IRON_BLOCK("raw_iron_block"), RED_CANDLE("red_candle"), RED_CANDLE_LIT("red_candle_lit"),
      RED_CONCRETE("red_concrete"), RED_CONCRETE_POWDER("red_concrete_powder"),
      RED_GLAZED_TERRACOTTA("red_glazed_terracotta"), RED_MUSHROOM("red_mushroom"),
      RED_MUSHROOM_BLOCK("red_mushroom_block"), RED_NETHER_BRICKS("red_nether_bricks"),
	  FROGSPAWN("frogspawn"),
	  FROSTED_ICE_0("frosted_ice_0"),
	  FROSTED_ICE_1("frosted_ice_1"),
	  FROSTED_ICE_2("frosted_ice_2"),
	  FROSTED_ICE_3("frosted_ice_3"),
      REDSTONE_DUST_DOT("redstone_dust_dot"), REDSTONE_DUST_LINE0("redstone_dust_line0"),
      REDSTONE_DUST_LINE1("redstone_dust_line1"), REDSTONE_DUST_OVERLAY("redstone_dust_overlay"),
      REDSTONE_LAMP("redstone_lamp"), REDSTONE_LAMP_ON("redstone_lamp_on"),
      REDSTONE_ORE("redstone_ore"), REDSTONE_TORCH("redstone_torch"),
      REDSTONE_TORCH_OFF("redstone_torch_off"),
      REINFORCED_DEEPSLATE_BOTTOM("reinforced_deepslate_bottom"),
      REINFORCED_DEEPSLATE_SIDE("reinforced_deepslate_side"),
      REINFORCED_DEEPSLATE_TOP("reinforced_deepslate_top"), REPEATER("repeater"),
      REPEATER_ON("repeater_on"), REPEATING_COMMAND_BLOCK_BACK("repeating_command_block_back"),
      REPEATING_COMMAND_BLOCK_CONDITIONAL("repeating_command_block_conditional"),
      REPEATING_COMMAND_BLOCK_FRONT("repeating_command_block_front"),
      REPEATING_COMMAND_BLOCK_SIDE("repeating_command_block_side"),
      RESPAWN_ANCHOR_BOTTOM("respawn_anchor_bottom"), RESPAWN_ANCHOR_SIDE0("respawn_anchor_side0"),
      RESPAWN_ANCHOR_SIDE1("respawn_anchor_side1"), RESPAWN_ANCHOR_SIDE2("respawn_anchor_side2"),
      RESPAWN_ANCHOR_SIDE3("respawn_anchor_side3"), RESPAWN_ANCHOR_SIDE4("respawn_anchor_side4"),
      RESPAWN_ANCHOR_TOP("respawn_anchor_top"), RESPAWN_ANCHOR_TOP_OFF("respawn_anchor_top_off"),
      ROOTED_DIRT("rooted_dirt"), ROSE_BUSH_BOTTOM("rose_bush_bottom"),
      ROSE_BUSH_TOP("rose_bush_top"), SAND("sand"), SANDSTONE("sandstone"),
	  GRASS_PATH_SIDE("grass_path_side"),
	  GRASS_PATH_TOP("grass_path_top"),
      SCAFFOLDING_TOP("scaffolding_top"), SCULK("sculk"),
      SCULK_CATALYST_BOTTOM("sculk_catalyst_bottom"), SCULK_CATALYST_SIDE("sculk_catalyst_side"),
      SCULK_CATALYST_SIDE_BLOOM("sculk_catalyst_side_bloom"),
      SCULK_CATALYST_TOP("sculk_catalyst_top"),
      SCULK_CATALYST_TOP_BLOOM("sculk_catalyst_top_bloom"),
      SCULK_SENSOR_BOTTOM("sculk_sensor_bottom"), SCULK_SENSOR_SIDE("sculk_sensor_side"),
      SCULK_SENSOR_TENDRIL_ACTIVE("sculk_sensor_tendril_active"),
      SCULK_SENSOR_TENDRIL_INACTIVE("sculk_sensor_tendril_inactive"),
      SCULK_SENSOR_TOP("sculk_sensor_top"), SCULK_SHRIEKER_BOTTOM("sculk_shrieker_bottom"),
      SCULK_SHRIEKER_CAN_SUMMON_INNER_TOP("sculk_shrieker_can_summon_inner_top"),
      SCULK_SHRIEKER_INNER_TOP("sculk_shrieker_inner_top"),
      SCULK_SHRIEKER_SIDE("sculk_shrieker_side"), SCULK_SHRIEKER_TOP("sculk_shrieker_top"),
      SCULK_VEIN("sculk_vein"), SEA_LANTERN("sea_lantern"), SEA_PICKLE("sea_pickle"),
      SEAGRASS("seagrass"), SHROOMLIGHT("shroomlight"), SHULKER_BOX("shulker_box"),
      SLIME_BLOCK("slime_block"), SMALL_AMETHYST_BUD("small_amethyst_bud"),
      SMALL_DRIPLEAF_SIDE("small_dripleaf_side"),
      SMALL_DRIPLEAF_STEM_BOTTOM("small_dripleaf_stem_bottom"),
      SMALL_DRIPLEAF_STEM_TOP("small_dripleaf_stem_top"), SMALL_DRIPLEAF_TOP("small_dripleaf_top"),
      SMITHING_TABLE_BOTTOM("smithing_table_bottom"), SMITHING_TABLE_FRONT("smithing_table_front"),
      SMITHING_TABLE_SIDE("smithing_table_side"), SMITHING_TABLE_TOP("smithing_table_top"),
      SMOKER_BOTTOM("smoker_bottom"), SMOKER_FRONT("smoker_front"),
      SMOKER_FRONT_ON("smoker_front_on"), SMOKER_SIDE("smoker_side"), SMOKER_TOP("smoker_top"),
      SMOOTH_BASALT("smooth_basalt"), SMOOTH_STONE("smooth_stone"),
      SMOOTH_STONE_SLAB_SIDE("smooth_stone_slab_side"), SNOW("snow"),
      SOUL_CAMPFIRE_FIRE("soul_campfire_fire"), SOUL_CAMPFIRE_LOG_LIT("soul_campfire_log_lit"),
      SOUL_FIRE_0("soul_fire_0"), SOUL_FIRE_1("soul_fire_1"), SOUL_LANTERN("soul_lantern"),
      SOUL_SAND("soul_sand"), SOUL_SOIL("soul_soil"), SOUL_TORCH("soul_torch"), SPAWNER("spawner"),
      SPONGE("sponge"), SPORE_BLOSSOM("spore_blossom"), SPORE_BLOSSOM_BASE("spore_blossom_base"),
      SPRUCE_DOOR_BOTTOM("spruce_door_bottom"), SPRUCE_DOOR_TOP("spruce_door_top"),
      SPRUCE_LEAVES("spruce_leaves"), SPRUCE_LOG("spruce_log"), SPRUCE_LOG_TOP("spruce_log_top"),
      SPRUCE_PLANKS("spruce_planks"), SPRUCE_SAPLING("spruce_sapling"),
      SPRUCE_TRAPDOOR("spruce_trapdoor"), STONE("stone"), STONE_BRICKS("stone_bricks"),
      STONECUTTER_BOTTOM("stonecutter_bottom"), STONECUTTER_SAW("stonecutter_saw"),
      STONECUTTER_SIDE("stonecutter_side"), STONECUTTER_TOP("stonecutter_top"),
      STRIPPED_ACACIA_LOG("stripped_acacia_log"),
      STRIPPED_ACACIA_LOG_TOP("stripped_acacia_log_top"), STRIPPED_BIRCH_LOG("stripped_birch_log"),
      STRIPPED_BIRCH_LOG_TOP("stripped_birch_log_top"),
      STRIPPED_CRIMSON_STEM("stripped_crimson_stem"),
      STRIPPED_CRIMSON_STEM_TOP("stripped_crimson_stem_top"),
      STRIPPED_DARK_OAK_LOG("stripped_dark_oak_log"),
      STRIPPED_DARK_OAK_LOG_TOP("stripped_dark_oak_log_top"),
      STRIPPED_JUNGLE_LOG("stripped_jungle_log"),
      STRIPPED_JUNGLE_LOG_TOP("stripped_jungle_log_top"),
	  IRON_TRAPDOOR("iron_trapdoor"),
      STRIPPED_MANGROVE_LOG_TOP("stripped_mangrove_log_top"), STRIPPED_OAK_LOG("stripped_oak_log"),
      STRIPPED_OAK_LOG_TOP("stripped_oak_log_top"), STRIPPED_SPRUCE_LOG("stripped_spruce_log"),
      STRIPPED_SPRUCE_LOG_TOP("stripped_spruce_log_top"),
      STRIPPED_WARPED_STEM("stripped_warped_stem"),
      STRIPPED_WARPED_STEM_TOP("stripped_warped_stem_top"), STRUCTURE_BLOCK("structure_block"),
      STRUCTURE_BLOCK_CORNER("structure_block_corner"),
      STRUCTURE_BLOCK_DATA("structure_block_data"), STRUCTURE_BLOCK_LOAD("structure_block_load"),
      STRUCTURE_BLOCK_SAVE("structure_block_save"), SUGAR_CANE("sugar_cane"),
      SUNFLOWER_BACK("sunflower_back"), SUNFLOWER_BOTTOM("sunflower_bottom"),
      SUNFLOWER_FRONT("sunflower_front"), SUNFLOWER_TOP("sunflower_top"),
      SWEET_BERRY_BUSH_STAGE0("sweet_berry_bush_stage0"),
      SWEET_BERRY_BUSH_STAGE1("sweet_berry_bush_stage1"),
      SWEET_BERRY_BUSH_STAGE2("sweet_berry_bush_stage2"),
      SWEET_BERRY_BUSH_STAGE3("sweet_berry_bush_stage3"), TALL_GRASS_BOTTOM("tall_grass_bottom"),
      TALL_GRASS_TOP("tall_grass_top"), TALL_SEAGRASS_BOTTOM("tall_seagrass_bottom"),
      TALL_SEAGRASS_TOP("tall_seagrass_top"), TARGET_SIDE("target_side"), TARGET_TOP("target_top"),
      TERRACOTTA("terracotta"), TINTED_GLASS("tinted_glass"), TNT_BOTTOM("tnt_bottom"),
      TNT_SIDE("tnt_side"), TNT_TOP("tnt_top"), TORCH("torch"), TRIPWIRE("tripwire"),
      TRIPWIRE_HOOK("tripwire_hook"), TUBE_CORAL("tube_coral"),
      TUBE_CORAL_BLOCK("tube_coral_block"), TUBE_CORAL_FAN("tube_coral_fan"), TUFF("tuff"),
      TURTLE_EGG("turtle_egg"), TURTLE_EGG_SLIGHTLY_CRACKED("turtle_egg_slightly_cracked"),
      TURTLE_EGG_VERY_CRACKED("turtle_egg_very_cracked"), TWISTING_VINES("twisting_vines"),
      TWISTING_VINES_PLANT("twisting_vines_plant"),
      VERDANT_FROGLIGHT_SIDE("verdant_froglight_side"),
      VERDANT_FROGLIGHT_TOP("verdant_froglight_top"), VINE("vine"),
      WARPED_DOOR_BOTTOM("warped_door_bottom"), WARPED_DOOR_TOP("warped_door_top"),
      WARPED_FUNGUS("warped_fungus"), WARPED_NYLIUM("warped_nylium"),
      WARPED_NYLIUM_SIDE("warped_nylium_side"), WARPED_PLANKS("warped_planks"),
      WARPED_ROOTS("warped_roots"), WARPED_ROOTS_POT("warped_roots_pot"),
      WARPED_STEM("warped_stem"), WARPED_STEM_TOP("warped_stem_top"),
      WARPED_TRAPDOOR("warped_trapdoor"), WARPED_WART_BLOCK("warped_wart_block"),
      WATER_FLOW("water_flow"), WATER_OVERLAY("water_overlay"), WATER_STILL("water_still"),
      WEATHERED_COPPER("weathered_copper"), WEATHERED_CUT_COPPER("weathered_cut_copper"),
      WEEPING_VINES("weeping_vines"), WEEPING_VINES_PLANT("weeping_vines_plant"),
      WET_SPONGE("wet_sponge"), WHEAT_STAGE0("wheat_stage0"), WHEAT_STAGE1("wheat_stage1"),
      WHEAT_STAGE2("wheat_stage2"), WHEAT_STAGE3("wheat_stage3"), WHEAT_STAGE4("wheat_stage4"),
      WHEAT_STAGE5("wheat_stage5"), WHEAT_STAGE6("wheat_stage6"), WHEAT_STAGE7("wheat_stage7"),
      WHITE_CANDLE("white_candle"), WHITE_CANDLE_LIT("white_candle_lit"),
      WHITE_CONCRETE("white_concrete"), WHITE_CONCRETE_POWDER("white_concrete_powder"),
      WHITE_GLAZED_TERRACOTTA("white_glazed_terracotta"), WHITE_SHULKER_BOX("white_shulker_box"),
      WHITE_STAINED_GLASS("white_stained_glass"),
      WHITE_STAINED_GLASS_PANE_TOP("white_stained_glass_pane_top"),
      WHITE_TERRACOTTA("white_terracotta"), WHITE_TULIP("white_tulip"), WHITE_WOOL("white_wool"),
      WITHER_ROSE("wither_rose"), YELLOW_CANDLE("yellow_candle"),
      YELLOW_CANDLE_LIT("yellow_candle_lit"), YELLOW_CONCRETE("yellow_concrete"),
      YELLOW_CONCRETE_POWDER("yellow_concrete_powder"),
      YELLOW_GLAZED_TERRACOTTA("yellow_glazed_terracotta"),
      YELLOW_SHULKER_BOX("yellow_shulker_box"), YELLOW_STAINED_GLASS("yellow_stained_glass"),
      YELLOW_STAINED_GLASS_PANE_TOP("yellow_stained_glass_pane_top"),
      YELLOW_TERRACOTTA("yellow_terracotta"), YELLOW_WOOL("yellow_wool"),
      textures({
          &ACACIA_DOOR_BOTTOM,
          &ACACIA_DOOR_TOP,
          &ACACIA_LEAVES,
          &ACACIA_LOG,
          &ACACIA_LOG_TOP,
          &ACACIA_PLANKS,
          &ACACIA_SAPLING,
          &ACACIA_TRAPDOOR,
          &ACTIVATOR_RAIL,
          &ACTIVATOR_RAIL_ON,
          &ALLIUM,
          &AMETHYST_BLOCK,
          &AMETHYST_CLUSTER,
          &ANCIENT_DEBRIS_SIDE,
          &ANCIENT_DEBRIS_TOP,
          &ANDESITE,
          &ANVIL,
          &ANVIL_TOP,
          &ATTACHED_MELON_STEM,
          &ATTACHED_PUMPKIN_STEM,
          &AZALEA_LEAVES,
          &AZALEA_PLANT,
          &AZALEA_SIDE,
          &AZALEA_TOP,
          &AZURE_BLUET,
          &BAMBOO_LARGE_LEAVES,
          &BAMBOO_SINGLELEAF,
          &BAMBOO_SMALL_LEAVES,
          &BAMBOO_STAGE0,
          &BAMBOO_STALK,
          &BARREL_BOTTOM,
          &BARREL_SIDE,
          &BARREL_TOP,
          &BARREL_TOP_OPEN,
	  MANGROVE_DOOR_BOTTOM("mangrove_door_bottom"),
	  MANGROVE_DOOR_TOP("mangrove_door_top"),
	  MANGROVE_LEAVES("mangrove_leaves"),
	  MANGROVE_LOG("mangrove_log"),
	  MANGROVE_LOG_TOP("mangrove_log_top"),
	  MANGROVE_PLANKS("mangrove_planks"),
	  MANGROVE_PROPAGULE("mangrove_propagule"),
	  MANGROVE_PROPAGULE_HANGING("mangrove_propagule_hanging"),
	  MANGROVE_ROOTS_SIDE("mangrove_roots_side"),
	  MANGROVE_ROOTS_TOP("mangrove_roots_top"),
	  MANGROVE_TRAPDOOR("mangrove_trapdoor"),
          &BEEHIVE_FRONT_HONEY,
          &BEEHIVE_SIDE,
          &BEETROOTS_STAGE0,
          &BEETROOTS_STAGE1,
          &BEETROOTS_STAGE2,
          &BEETROOTS_STAGE3,
          &BELL_BOTTOM,
	  MUD("mud"),
	  MUD_BRICKS("mud_bricks"),
	  MUDDY_MANGROVE_ROOTS_SIDE("muddy_mangrove_roots_side"),
	  MUDDY_MANGROVE_ROOTS_TOP("muddy_mangrove_roots_top"),
          &BIG_DRIPLEAF_TIP,
          &BIG_DRIPLEAF_TOP,
          &BIRCH_DOOR_BOTTOM,
          &BIRCH_DOOR_TOP,
          &BIRCH_LEAVES,
          &BIRCH_LOG,
          &BIRCH_LOG_TOP,
          &BIRCH_PLANKS,
          &BIRCH_SAPLING,
          &BIRCH_TRAPDOOR,
          &BLACK_CANDLE,
          &BLACK_CANDLE_LIT,
          &BLACK_CONCRETE,
          &BLACK_CONCRETE_POWDER,
          &BLACK_GLAZED_TERRACOTTA,
          &BLACK_SHULKER_BOX,
          &BLACK_STAINED_GLASS,
          &BLACK_STAINED_GLASS_PANE_TOP,
          &BLACK_TERRACOTTA,
          &BLACK_WOOL,
          &BLACKSTONE,
          &BLACKSTONE_TOP,
          &BLAST_FURNACE_FRONT,
          &BLAST_FURNACE_FRONT_ON,
	  OBSERVER_BACK("observer_back"),
          &BLAST_FURNACE_TOP,
	  OBSERVER_FRONT("observer_front"),
	  OBSERVER_SIDE("observer_side"),
	  OBSERVER_TOP("observer_top"),
          &BLUE_CONCRETE_POWDER,
	  OCHRE_FROGLIGHT_SIDE("ochre_froglight_side"),
	  OCHRE_FROGLIGHT_TOP("ochre_froglight_top"),
          &BLUE_ORCHID,
          &BLUE_SHULKER_BOX,
          &BLUE_STAINED_GLASS,
          &BLUE_STAINED_GLASS_PANE_TOP,
          &BLUE_TERRACOTTA,
          &BLUE_WOOL,
          &BONE_BLOCK_SIDE,
          &BONE_BLOCK_TOP,
          &BOOKSHELF,
          &BRAIN_CORAL,
          &BRAIN_CORAL_BLOCK,
          &BRAIN_CORAL_FAN,
          &BREWING_STAND,
          &BREWING_STAND_BASE,
          &BRICKS,
	  PACKED_MUD("packed_mud"),
	  PEARLESCENT_FROGLIGHT_SIDE("pearlescent_froglight_side"),
	  PEARLESCENT_FROGLIGHT_TOP("pearlescent_froglight_top"),
          &BROWN_CONCRETE_POWDER,
          &BROWN_GLAZED_TERRACOTTA,
          &BROWN_MUSHROOM,
          &BROWN_MUSHROOM_BLOCK,
          &BROWN_SHULKER_BOX,
          &BROWN_STAINED_GLASS,
          &BROWN_STAINED_GLASS_PANE_TOP,
          &BROWN_TERRACOTTA,
          &BROWN_WOOL,
          &BUBBLE_CORAL,
          &BUBBLE_CORAL_BLOCK,
          &BUBBLE_CORAL_FAN,
          &BUDDING_AMETHYST,
          &CACTUS_BOTTOM,
          &CACTUS_SIDE,
          &CACTUS_TOP,
          &CAKE_BOTTOM,
          &CAKE_INNER,
          &CAKE_SIDE,
          &CAKE_TOP,
          &CALCITE,
          &CAMPFIRE_FIRE,
          &CAMPFIRE_LOG,
          &CAMPFIRE_LOG_LIT,
          &CANDLE,
          &CANDLE_LIT,
          &CARROTS_STAGE0,
          &CARROTS_STAGE1,
          &CARROTS_STAGE2,
          &CARROTS_STAGE3,
          &CARTOGRAPHY_TABLE_SIDE1,
          &CARTOGRAPHY_TABLE_SIDE2,
          &CARTOGRAPHY_TABLE_SIDE3,
          &CARTOGRAPHY_TABLE_TOP,
          &CARVED_PUMPKIN,
          &CAULDRON_BOTTOM,
          &CAULDRON_INNER,
          &CAULDRON_SIDE,
          &CAULDRON_TOP,
          &CAVE_VINES,
          &CAVE_VINES_LIT,
          &CAVE_VINES_PLANT,
          &CAVE_VINES_PLANT_LIT,
          &CHAIN,
          &CHAIN_COMMAND_BLOCK_BACK,
          &CHAIN_COMMAND_BLOCK_CONDITIONAL,
          &CHAIN_COMMAND_BLOCK_FRONT,
          &CHAIN_COMMAND_BLOCK_SIDE,
          &CHIPPED_ANVIL_TOP,
          &CHISELED_DEEPSLATE,
          &CHISELED_NETHER_BRICKS,
          &CHISELED_POLISHED_BLACKSTONE,
          &CHISELED_QUARTZ_BLOCK,
	  PRISMARINE_BRICKS("prismarine_bricks"),
          &CHISELED_RED_SANDSTONE,
          &CHISELED_SANDSTONE,
          &CHISELED_STONE_BRICKS,
          &CHORUS_FLOWER,
          &CHORUS_FLOWER_DEAD,
          &CHORUS_PLANT,
          &CLAY,
          &COAL_BLOCK,
          &COAL_ORE,
          &COARSE_DIRT,
          &COBBLED_DEEPSLATE,
          &COBBLESTONE,
          &COBWEB,
	  PURPUR_BLOCK("purpur_block"),
	  PURPUR_PILLAR("purpur_pillar"),
	  PURPUR_PILLAR_TOP("purpur_pillar_top"),
          &COMMAND_BLOCK_BACK,
          &COMMAND_BLOCK_CONDITIONAL,
          &COMMAND_BLOCK_FRONT,
          &COMMAND_BLOCK_SIDE,
          &COMPARATOR,
          &COMPARATOR_ON,
          &COMPOSTER_BOTTOM,
          &COMPOSTER_COMPOST,
          &COMPOSTER_READY,
          &COMPOSTER_SIDE,
          &COMPOSTER_TOP,
          &CONDUIT,
          &COPPER_BLOCK,
          &COPPER_ORE,
          &CORNFLOWER,
          &CRACKED_DEEPSLATE_BRICKS,
          &CRACKED_DEEPSLATE_TILES,
          &CRACKED_NETHER_BRICKS,
          &CRACKED_POLISHED_BLACKSTONE_BRICKS,
          &CRACKED_STONE_BRICKS,
          &CRAFTING_TABLE_FRONT,
	  RED_SANDSTONE_BOTTOM("red_sandstone_bottom"),
	  RED_SANDSTONE_TOP("red_sandstone_top"),
          &CRIMSON_DOOR_BOTTOM,
          &CRIMSON_DOOR_TOP,
          &CRIMSON_FUNGUS,
          &CRIMSON_NYLIUM,
          &CRIMSON_NYLIUM_SIDE,
          &CRIMSON_PLANKS,
          &CRIMSON_ROOTS,
	  REDSTONE_DUST_DOT("redstone_dust_dot"),
	  REDSTONE_DUST_LINE0("redstone_dust_line0"),
	  REDSTONE_DUST_LINE1("redstone_dust_line1"),
	  REDSTONE_DUST_OVERLAY("redstone_dust_overlay"),
          &CRYING_OBSIDIAN,
          &CUT_COPPER,
          &CUT_RED_SANDSTONE,
          &CUT_SANDSTONE,
          &CYAN_CANDLE,
	  REINFORCED_DEEPSLATE_BOTTOM("reinforced_deepslate_bottom"),
	  REINFORCED_DEEPSLATE_SIDE("reinforced_deepslate_side"),
	  REINFORCED_DEEPSLATE_TOP("reinforced_deepslate_top"),
          &CYAN_GLAZED_TERRACOTTA,
          &CYAN_SHULKER_BOX,
	  REPEATING_COMMAND_BLOCK_BACK("repeating_command_block_back"),
	  REPEATING_COMMAND_BLOCK_CONDITIONAL("repeating_command_block_conditional"),
	  REPEATING_COMMAND_BLOCK_FRONT("repeating_command_block_front"),
	  REPEATING_COMMAND_BLOCK_SIDE("repeating_command_block_side"),
          &DAMAGED_ANVIL_TOP,
          &DANDELION,
          &DARK_OAK_DOOR_BOTTOM,
          &DARK_OAK_DOOR_TOP,
          &DARK_OAK_LEAVES,
          &DARK_OAK_LOG,
          &DARK_OAK_LOG_TOP,
          &DARK_OAK_PLANKS,
          &DARK_OAK_SAPLING,
          &DARK_OAK_TRAPDOOR,
          &DARK_PRISMARINE,
          &DAYLIGHT_DETECTOR_INVERTED_TOP,
          &DAYLIGHT_DETECTOR_SIDE,
          &DAYLIGHT_DETECTOR_TOP,
          &DEAD_BRAIN_CORAL,
          &DEAD_BRAIN_CORAL_BLOCK,
          &DEAD_BRAIN_CORAL_FAN,
          &DEAD_BUBBLE_CORAL,
	  SCULK("sculk"),
	  SCULK_CATALYST_BOTTOM("sculk_catalyst_bottom"),
	  SCULK_CATALYST_SIDE("sculk_catalyst_side"),
	  SCULK_CATALYST_SIDE_BLOOM("sculk_catalyst_side_bloom"),
	  SCULK_CATALYST_TOP("sculk_catalyst_top"),
	  SCULK_CATALYST_TOP_BLOOM("sculk_catalyst_top_bloom"),
          &DEAD_HORN_CORAL,
          &DEAD_HORN_CORAL_BLOCK,
          &DEAD_HORN_CORAL_FAN,
          &DEAD_TUBE_CORAL,
          &DEAD_TUBE_CORAL_BLOCK,
	  SCULK_SHRIEKER_BOTTOM("sculk_shrieker_bottom"),
	  SCULK_SHRIEKER_CAN_SUMMON_INNER_TOP("sculk_shrieker_can_summon_inner_top"),
	  SCULK_SHRIEKER_INNER_TOP("sculk_shrieker_inner_top"),
	  SCULK_SHRIEKER_SIDE("sculk_shrieker_side"),
	  SCULK_SHRIEKER_TOP("sculk_shrieker_top"),
	  SCULK_VEIN("sculk_vein"),
	  SEA_LANTERN("sea_lantern"),
          &DEEPSLATE_DIAMOND_ORE,
          &DEEPSLATE_EMERALD_ORE,
          &DEEPSLATE_GOLD_ORE,
          &DEEPSLATE_IRON_ORE,
          &DEEPSLATE_LAPIS_ORE,
          &DEEPSLATE_REDSTONE_ORE,
          &DEEPSLATE_TILES,
          &DEEPSLATE_TOP,
          &DESTROY_STAGE_0,
          &DESTROY_STAGE_1,
          &DESTROY_STAGE_2,
          &DESTROY_STAGE_3,
          &DESTROY_STAGE_4,
          &DESTROY_STAGE_5,
          &DESTROY_STAGE_6,
          &DESTROY_STAGE_7,
          &DESTROY_STAGE_8,
          &DESTROY_STAGE_9,
          &DETECTOR_RAIL,
          &DETECTOR_RAIL_ON,
          &DIAMOND_BLOCK,
          &DIAMOND_ORE,
          &DIORITE,
          &DIRT,
          &DIRT_PATH_SIDE,
          &DIRT_PATH_TOP,
          &DISPENSER_FRONT,
          &DISPENSER_FRONT_VERTICAL,
          &DRAGON_EGG,
          &DRIED_KELP_BOTTOM,
          &DRIED_KELP_SIDE,
          &DRIED_KELP_TOP,
          &DRIPSTONE_BLOCK,
          &DROPPER_FRONT,
          &DROPPER_FRONT_VERTICAL,
          &EMERALD_BLOCK,
          &EMERALD_ORE,
          &ENCHANTING_TABLE_BOTTOM,
          &ENCHANTING_TABLE_SIDE,
          &ENCHANTING_TABLE_TOP,
          &END_PORTAL_FRAME_EYE,
          &END_PORTAL_FRAME_SIDE,
          &END_PORTAL_FRAME_TOP,
          &END_ROD,
          &END_STONE,
          &END_STONE_BRICKS,
          &EXPOSED_COPPER,
          &EXPOSED_CUT_COPPER,
          &FARMLAND,
          &FARMLAND_MOIST,
          &FERN,
          &FIRE_0,
          &FIRE_1,
          &FIRE_CORAL,
          &FIRE_CORAL_BLOCK,
          &FIRE_CORAL_FAN,
          &FLETCHING_TABLE_FRONT,
          &FLETCHING_TABLE_SIDE,
          &FLETCHING_TABLE_TOP,
	  STRIPPED_MANGROVE_LOG("stripped_mangrove_log"),
	  STRIPPED_MANGROVE_LOG_TOP("stripped_mangrove_log_top"),
          &FLOWERING_AZALEA_SIDE,
          &FLOWERING_AZALEA_TOP,
          &FROGSPAWN,
          &FROSTED_ICE_0,
          &FROSTED_ICE_1,
          &FROSTED_ICE_2,
	  STRUCTURE_BLOCK("structure_block"),
	  STRUCTURE_BLOCK_CORNER("structure_block_corner"),
	  STRUCTURE_BLOCK_DATA("structure_block_data"),
	  STRUCTURE_BLOCK_LOAD("structure_block_load"),
	  STRUCTURE_BLOCK_SAVE("structure_block_save"),
          &GILDED_BLACKSTONE,
          &GLASS,
          &GLASS_PANE_TOP,
          &GLOW_ITEM_FRAME,
          &GLOW_LICHEN,
          &GLOWSTONE,
          &GOLD_BLOCK,
          &GOLD_ORE,
          &GRANITE,
          &GRASS,
          &GRASS_BLOCK_SIDE,
          &GRASS_BLOCK_SIDE_OVERLAY,
          &GRASS_BLOCK_SNOW,
          &GRASS_BLOCK_TOP,
          &GRASS_PATH_SIDE,
          &GRASS_PATH_TOP,
          &GRAVEL,
          &GRAY_CANDLE,
          &GRAY_CANDLE_LIT,
          &GRAY_CONCRETE,
          &GRAY_CONCRETE_POWDER,
          &GRAY_GLAZED_TERRACOTTA,
          &GRAY_SHULKER_BOX,
          &GRAY_STAINED_GLASS,
          &GRAY_STAINED_GLASS_PANE_TOP,
          &GRAY_TERRACOTTA,
          &GRAY_WOOL,
          &GREEN_CANDLE,
          &GREEN_CANDLE_LIT,
          &GREEN_CONCRETE,
          &GREEN_CONCRETE_POWDER,
          &GREEN_GLAZED_TERRACOTTA,
	  VERDANT_FROGLIGHT_SIDE("verdant_froglight_side"),
	  VERDANT_FROGLIGHT_TOP("verdant_froglight_top"),
          &GREEN_STAINED_GLASS_PANE_TOP,
          &GREEN_TERRACOTTA,
          &GREEN_WOOL,
          &GRINDSTONE_PIVOT,
          &GRINDSTONE_ROUND,
          &GRINDSTONE_SIDE,
          &HANGING_ROOTS,
          &HAY_BLOCK_SIDE,
          &HAY_BLOCK_TOP,
          &HONEY_BLOCK_BOTTOM,
          &HONEY_BLOCK_SIDE,
          &HONEY_BLOCK_TOP,
          &HONEYCOMB_BLOCK,
          &HOPPER_INSIDE,
	  WATER_OVERLAY("water_overlay"),
          &HOPPER_TOP,
          &HORN_CORAL,
          &HORN_CORAL_BLOCK,
          &HORN_CORAL_FAN,
          &ICE,
          &IRON_BARS,
          &IRON_BLOCK,
          &IRON_DOOR_BOTTOM,
          &IRON_DOOR_TOP,
          &IRON_ORE,
          &IRON_TRAPDOOR,
          &ITEM_FRAME,
          &JACK_O_LANTERN,
          &JIGSAW_BOTTOM,
          &JIGSAW_LOCK,
          &JIGSAW_SIDE,
          &JIGSAW_TOP,
          &JUKEBOX_SIDE,
          &JUKEBOX_TOP,
          &JUNGLE_DOOR_BOTTOM,
          &JUNGLE_DOOR_TOP,
          &JUNGLE_LEAVES,
          &JUNGLE_LOG,
          &JUNGLE_LOG_TOP,
          &JUNGLE_PLANKS,
          &JUNGLE_SAPLING,
          &JUNGLE_TRAPDOOR,
          &KELP,
          &KELP_PLANT,
          &LADDER,
          &LANTERN,
          &LAPIS_BLOCK,
          &LAPIS_ORE,
          &LARGE_AMETHYST_BUD,
          &LARGE_FERN_BOTTOM,
          &LARGE_FERN_TOP,
          &LAVA_FLOW,
          &LAVA_STILL,
          &LECTERN_BASE,
          &LECTERN_FRONT,
          &LECTERN_SIDES,
          &LECTERN_TOP,
          &LEVER,
          &LIGHT_BLUE_CANDLE,
          &LIGHT_BLUE_CANDLE_LIT,
          &LIGHT_BLUE_CONCRETE,
          &LIGHT_BLUE_CONCRETE_POWDER,
          &LIGHT_BLUE_GLAZED_TERRACOTTA,
          &LIGHT_BLUE_SHULKER_BOX,
          &LIGHT_BLUE_STAINED_GLASS,
          &LIGHT_BLUE_STAINED_GLASS_PANE_TOP,
          &LIGHT_BLUE_TERRACOTTA,
          &LIGHT_BLUE_WOOL,
          &LIGHT_GRAY_CANDLE,
          &LIGHT_GRAY_CANDLE_LIT,
          &LIGHT_GRAY_CONCRETE,
          &LIGHT_GRAY_CONCRETE_POWDER,
          &LIGHT_GRAY_GLAZED_TERRACOTTA,
          &LIGHT_GRAY_SHULKER_BOX,
          &LIGHT_GRAY_STAINED_GLASS,
          &LIGHT_GRAY_STAINED_GLASS_PANE_TOP,
          &LIGHT_GRAY_TERRACOTTA,
          &LIGHT_GRAY_WOOL,
          &LIGHTNING_ROD,
          &LIGHTNING_ROD_ON,
          &LILAC_BOTTOM,
          &LILAC_TOP,
          &LILY_OF_THE_VALLEY,
          &LILY_PAD,
          &LIME_CANDLE,
          &LIME_CANDLE_LIT,
          &LIME_CONCRETE,
          &LIME_CONCRETE_POWDER,
          &LIME_GLAZED_TERRACOTTA,
          &LIME_SHULKER_BOX,
          &LIME_STAINED_GLASS,
          &LIME_STAINED_GLASS_PANE_TOP,
          &LIME_TERRACOTTA,
          &LIME_WOOL,
          &LODESTONE_SIDE,
          &LODESTONE_TOP,
          &LOOM_BOTTOM,
          &LOOM_FRONT,
          &LOOM_SIDE,
          &LOOM_TOP,
          &MAGENTA_CANDLE,
          &MAGENTA_CANDLE_LIT,
          &MAGENTA_CONCRETE,
          &MAGENTA_CONCRETE_POWDER,
          &MAGENTA_GLAZED_TERRACOTTA,
          &MAGENTA_SHULKER_BOX,
          &MAGENTA_STAINED_GLASS,
          &MAGENTA_STAINED_GLASS_PANE_TOP,
          &MAGENTA_TERRACOTTA,
          &MAGENTA_WOOL,
          &MAGMA,
          &MANGROVE_DOOR_BOTTOM,
          &MANGROVE_DOOR_TOP,
          &MANGROVE_LEAVES,
          &MANGROVE_LOG,
          &MANGROVE_LOG_TOP,
          &MANGROVE_PLANKS,
          &MANGROVE_PROPAGULE,
          &MANGROVE_PROPAGULE_HANGING,
          &MANGROVE_ROOTS_SIDE,
          &MANGROVE_ROOTS_TOP,
          &MANGROVE_TRAPDOOR,
          &MEDIUM_AMETHYST_BUD,
          &MELON_SIDE,
          &MELON_STEM,
          &MELON_TOP,
          &MOSS_BLOCK,
          &MOSSY_COBBLESTONE,
          &MOSSY_STONE_BRICKS,
          &MUD,
          &MUD_BRICKS,
          &MUDDY_MANGROVE_ROOTS_SIDE,
          &MUDDY_MANGROVE_ROOTS_TOP,
          &MUSHROOM_BLOCK_INSIDE,
          &MUSHROOM_STEM,
          &MYCELIUM_SIDE,
          &MYCELIUM_TOP,
          &NETHER_BRICKS,
          &NETHER_GOLD_ORE,
          &NETHER_PORTAL,
          &NETHER_QUARTZ_ORE,
          &NETHER_SPROUTS,
          &NETHER_WART_BLOCK,
          &NETHER_WART_STAGE0,
          &NETHER_WART_STAGE1,
          &NETHER_WART_STAGE2,
          &NETHERITE_BLOCK,
          &NETHERRACK,
          &NOTE_BLOCK,
          &OAK_DOOR_BOTTOM,
          &OAK_DOOR_TOP,
          &OAK_LEAVES,
          &OAK_LOG,
          &OAK_LOG_TOP,
          &OAK_PLANKS,
          &OAK_SAPLING,
          &OAK_TRAPDOOR,
          &OBSERVER_BACK,
          &OBSERVER_BACK_ON,
          &OBSERVER_FRONT,
          &OBSERVER_SIDE,
          &OBSERVER_TOP,
          &OBSIDIAN,
          &OCHRE_FROGLIGHT_SIDE,
          &OCHRE_FROGLIGHT_TOP,
          &ORANGE_CANDLE,
          &ORANGE_CANDLE_LIT,
          &ORANGE_CONCRETE,
          &ORANGE_CONCRETE_POWDER,
          &ORANGE_GLAZED_TERRACOTTA,
          &ORANGE_SHULKER_BOX,
          &ORANGE_STAINED_GLASS,
          &ORANGE_STAINED_GLASS_PANE_TOP,
          &ORANGE_TERRACOTTA,
          &ORANGE_TULIP,
          &ORANGE_WOOL,
          &OXEYE_DAISY,
          &OXIDIZED_COPPER,
          &OXIDIZED_CUT_COPPER,
          &PACKED_ICE,
          &PACKED_MUD,
          &PEARLESCENT_FROGLIGHT_SIDE,
          &PEARLESCENT_FROGLIGHT_TOP,
          &PEONY_BOTTOM,
          &PEONY_TOP,
          &PINK_CANDLE,
          &PINK_CANDLE_LIT,
          &PINK_CONCRETE,
          &PINK_CONCRETE_POWDER,
          &PINK_GLAZED_TERRACOTTA,
          &PINK_SHULKER_BOX,
          &PINK_STAINED_GLASS,
          &PINK_STAINED_GLASS_PANE_TOP,
          &PINK_TERRACOTTA,
          &PINK_TULIP,
          &PINK_WOOL,
          &PISTON_BOTTOM,
          &PISTON_INNER,
          &PISTON_SIDE,
          &PISTON_TOP,
          &PISTON_TOP_STICKY,
	             &CHAIN_COMMAND_BLOCK_BACK,
	             &CHAIN_COMMAND_BLOCK_CONDITIONAL,
	             &CHAIN_COMMAND_BLOCK_FRONT,
	             &CHAIN_COMMAND_BLOCK_SIDE,
          &POINTED_DRIPSTONE_DOWN_MIDDLE,
          &POINTED_DRIPSTONE_DOWN_TIP,
          &POINTED_DRIPSTONE_DOWN_TIP_MERGE,
          &POINTED_DRIPSTONE_UP_BASE,
          &POINTED_DRIPSTONE_UP_FRUSTUM,
          &POINTED_DRIPSTONE_UP_MIDDLE,
          &POINTED_DRIPSTONE_UP_TIP,
          &POINTED_DRIPSTONE_UP_TIP_MERGE,
          &POLISHED_ANDESITE,
	             &CHORUS_FLOWER,
	             &CHORUS_FLOWER_DEAD,
	             &CHORUS_PLANT,
          &POLISHED_BLACKSTONE_BRICKS,
          &POLISHED_DEEPSLATE,
          &POLISHED_DIORITE,
	             &COARSE_DIRT,
          &POPPY,
          &POTATOES_STAGE0,
          &POTATOES_STAGE1,
          &POTATOES_STAGE2,
          &POTATOES_STAGE3,
          &POTTED_AZALEA_BUSH_PLANT,
	             &COMMAND_BLOCK_BACK,
	             &COMMAND_BLOCK_CONDITIONAL,
	             &COMMAND_BLOCK_FRONT,
	             &COMMAND_BLOCK_SIDE,
          &POTTED_FLOWERING_AZALEA_BUSH_TOP,
          &POWDER_SNOW,
          &POWERED_RAIL,
          &POWERED_RAIL_ON,
          &PRISMARINE,
          &PRISMARINE_BRICKS,
          &PUMPKIN_SIDE,
          &PUMPKIN_STEM,
          &PUMPKIN_TOP,
          &PURPLE_CANDLE,
          &PURPLE_CANDLE_LIT,
          &PURPLE_CONCRETE,
          &PURPLE_CONCRETE_POWDER,
          &PURPLE_GLAZED_TERRACOTTA,
          &PURPLE_SHULKER_BOX,
          &PURPLE_STAINED_GLASS,
          &PURPLE_STAINED_GLASS_PANE_TOP,
          &PURPLE_TERRACOTTA,
          &PURPLE_WOOL,
          &PURPUR_BLOCK,
          &PURPUR_PILLAR,
          &PURPUR_PILLAR_TOP,
          &QUARTZ_BLOCK_BOTTOM,
          &QUARTZ_BLOCK_SIDE,
          &QUARTZ_BLOCK_TOP,
          &QUARTZ_BRICKS,
          &QUARTZ_PILLAR,
          &QUARTZ_PILLAR_TOP,
          &RAIL,
          &RAIL_CORNER,
          &RAW_COPPER_BLOCK,
          &RAW_GOLD_BLOCK,
          &RAW_IRON_BLOCK,
          &RED_CANDLE,
          &RED_CANDLE_LIT,
          &RED_CONCRETE,
          &RED_CONCRETE_POWDER,
          &RED_GLAZED_TERRACOTTA,
          &RED_MUSHROOM,
          &RED_MUSHROOM_BLOCK,
          &RED_NETHER_BRICKS,
          &RED_SAND,
          &RED_SANDSTONE,
          &RED_SANDSTONE_BOTTOM,
          &RED_SANDSTONE_TOP,
          &RED_SHULKER_BOX,
          &RED_STAINED_GLASS,
          &RED_STAINED_GLASS_PANE_TOP,
          &RED_TERRACOTTA,
          &RED_TULIP,
          &RED_WOOL,
          &REDSTONE_BLOCK,
          &REDSTONE_DUST_DOT,
          &REDSTONE_DUST_LINE0,
          &REDSTONE_DUST_LINE1,
	             &DAYLIGHT_DETECTOR_INVERTED_TOP,
          &REDSTONE_LAMP,
          &REDSTONE_LAMP_ON,
          &REDSTONE_ORE,
          &REDSTONE_TORCH,
          &REDSTONE_TORCH_OFF,
          &REINFORCED_DEEPSLATE_BOTTOM,
          &REINFORCED_DEEPSLATE_SIDE,
          &REINFORCED_DEEPSLATE_TOP,
          &REPEATER,
          &REPEATER_ON,
          &REPEATING_COMMAND_BLOCK_BACK,
          &REPEATING_COMMAND_BLOCK_CONDITIONAL,
          &REPEATING_COMMAND_BLOCK_FRONT,
          &REPEATING_COMMAND_BLOCK_SIDE,
          &RESPAWN_ANCHOR_BOTTOM,
          &RESPAWN_ANCHOR_SIDE0,
          &RESPAWN_ANCHOR_SIDE1,
          &RESPAWN_ANCHOR_SIDE2,
	             &DEBUG,
	             &DEBUG2,
          &RESPAWN_ANCHOR_TOP,
          &RESPAWN_ANCHOR_TOP_OFF,
          &ROOTED_DIRT,
          &ROSE_BUSH_BOTTOM,
          &ROSE_BUSH_TOP,
          &SAND,
          &SANDSTONE,
          &SANDSTONE_BOTTOM,
          &SANDSTONE_TOP,
          &SCAFFOLDING_BOTTOM,
          &SCAFFOLDING_SIDE,
          &SCAFFOLDING_TOP,
          &SCULK,
          &SCULK_CATALYST_BOTTOM,
          &SCULK_CATALYST_SIDE,
          &SCULK_CATALYST_SIDE_BLOOM,
          &SCULK_CATALYST_TOP,
          &SCULK_CATALYST_TOP_BLOOM,
          &SCULK_SENSOR_BOTTOM,
          &SCULK_SENSOR_SIDE,
          &SCULK_SENSOR_TENDRIL_ACTIVE,
          &SCULK_SENSOR_TENDRIL_INACTIVE,
          &SCULK_SENSOR_TOP,
          &SCULK_SHRIEKER_BOTTOM,
          &SCULK_SHRIEKER_CAN_SUMMON_INNER_TOP,
          &SCULK_SHRIEKER_INNER_TOP,
          &SCULK_SHRIEKER_SIDE,
          &SCULK_SHRIEKER_TOP,
          &SCULK_VEIN,
          &SEA_LANTERN,
          &SEA_PICKLE,
          &SEAGRASS,
          &SHROOMLIGHT,
          &SHULKER_BOX,
          &SLIME_BLOCK,
          &SMALL_AMETHYST_BUD,
          &SMALL_DRIPLEAF_SIDE,
          &SMALL_DRIPLEAF_STEM_BOTTOM,
          &SMALL_DRIPLEAF_STEM_TOP,
          &SMALL_DRIPLEAF_TOP,
          &SMITHING_TABLE_BOTTOM,
          &SMITHING_TABLE_FRONT,
          &SMITHING_TABLE_SIDE,
          &SMITHING_TABLE_TOP,
          &SMOKER_BOTTOM,
          &SMOKER_FRONT,
          &SMOKER_FRONT_ON,
	             &END_ROD,
          &SMOKER_TOP,
          &SMOOTH_BASALT,
          &SMOOTH_STONE,
          &SMOOTH_STONE_SLAB_SIDE,
          &SNOW,
          &SOUL_CAMPFIRE_FIRE,
          &SOUL_CAMPFIRE_LOG_LIT,
          &SOUL_FIRE_0,
          &SOUL_FIRE_1,
          &SOUL_LANTERN,
          &SOUL_SAND,
          &SOUL_SOIL,
          &SOUL_TORCH,
          &SPAWNER,
          &SPONGE,
          &SPORE_BLOSSOM,
          &SPORE_BLOSSOM_BASE,
          &SPRUCE_DOOR_BOTTOM,
          &SPRUCE_DOOR_TOP,
	             &FROGSPAWN,
	             &FROSTED_ICE_0,
	             &FROSTED_ICE_1,
	             &FROSTED_ICE_2,
	             &FROSTED_ICE_3,
          &SPRUCE_TRAPDOOR,
          &STONE,
          &STONE_BRICKS,
          &STONECUTTER_BOTTOM,
          &STONECUTTER_SAW,
          &STONECUTTER_SIDE,
          &STONECUTTER_TOP,
          &STRIPPED_ACACIA_LOG,
          &STRIPPED_ACACIA_LOG_TOP,
          &STRIPPED_BIRCH_LOG,
          &STRIPPED_BIRCH_LOG_TOP,
          &STRIPPED_CRIMSON_STEM,
          &STRIPPED_CRIMSON_STEM_TOP,
          &STRIPPED_DARK_OAK_LOG,
          &STRIPPED_DARK_OAK_LOG_TOP,
          &STRIPPED_JUNGLE_LOG,
          &STRIPPED_JUNGLE_LOG_TOP,
          &STRIPPED_MANGROVE_LOG,
	             &GRASS_PATH_SIDE,
	             &GRASS_PATH_TOP,
          &STRIPPED_OAK_LOG_TOP,
          &STRIPPED_SPRUCE_LOG,
          &STRIPPED_SPRUCE_LOG_TOP,
          &STRIPPED_WARPED_STEM,
          &STRIPPED_WARPED_STEM_TOP,
          &STRUCTURE_BLOCK,
          &STRUCTURE_BLOCK_CORNER,
          &STRUCTURE_BLOCK_DATA,
          &STRUCTURE_BLOCK_LOAD,
          &STRUCTURE_BLOCK_SAVE,
          &SUGAR_CANE,
          &SUNFLOWER_BACK,
          &SUNFLOWER_BOTTOM,
          &SUNFLOWER_FRONT,
          &SUNFLOWER_TOP,
          &SWEET_BERRY_BUSH_STAGE0,
          &SWEET_BERRY_BUSH_STAGE1,
          &SWEET_BERRY_BUSH_STAGE2,
          &SWEET_BERRY_BUSH_STAGE3,
          &TALL_GRASS_BOTTOM,
          &TALL_GRASS_TOP,
          &TALL_SEAGRASS_BOTTOM,
          &TALL_SEAGRASS_TOP,
          &TARGET_SIDE,
          &TARGET_TOP,
          &TERRACOTTA,
          &TINTED_GLASS,
          &TNT_BOTTOM,
          &TNT_SIDE,
          &TNT_TOP,
          &TORCH,
          &TRIPWIRE,
          &TRIPWIRE_HOOK,
          &TUBE_CORAL,
          &TUBE_CORAL_BLOCK,
          &TUBE_CORAL_FAN,
          &TUFF,
          &TURTLE_EGG,
          &TURTLE_EGG_SLIGHTLY_CRACKED,
          &TURTLE_EGG_VERY_CRACKED,
          &TWISTING_VINES,
          &TWISTING_VINES_PLANT,
          &VERDANT_FROGLIGHT_SIDE,
	             &IRON_TRAPDOOR,
          &VINE,
          &WARPED_DOOR_BOTTOM,
          &WARPED_DOOR_TOP,
          &WARPED_FUNGUS,
          &WARPED_NYLIUM,
          &WARPED_NYLIUM_SIDE,
          &WARPED_PLANKS,
          &WARPED_ROOTS,
          &WARPED_ROOTS_POT,
          &WARPED_STEM,
          &WARPED_STEM_TOP,
          &WARPED_TRAPDOOR,
          &WARPED_WART_BLOCK,
          &WATER_FLOW,
          &WATER_OVERLAY,
          &WATER_STILL,
          &WEATHERED_COPPER,
          &WEATHERED_CUT_COPPER,
          &WEEPING_VINES,
          &WEEPING_VINES_PLANT,
          &WET_SPONGE,
          &WHEAT_STAGE0,
          &WHEAT_STAGE1,
          &WHEAT_STAGE2,
          &WHEAT_STAGE3,
          &WHEAT_STAGE4,
          &WHEAT_STAGE5,
          &WHEAT_STAGE6,
          &WHEAT_STAGE7,
          &WHITE_CANDLE,
          &WHITE_CANDLE_LIT,
          &WHITE_CONCRETE,
          &WHITE_CONCRETE_POWDER,
          &WHITE_GLAZED_TERRACOTTA,
          &WHITE_SHULKER_BOX,
          &WHITE_STAINED_GLASS,
          &WHITE_STAINED_GLASS_PANE_TOP,
          &WHITE_TERRACOTTA,
          &WHITE_TULIP,
          &WHITE_WOOL,
          &WITHER_ROSE,
          &YELLOW_CANDLE,
          &YELLOW_CANDLE_LIT,
          &YELLOW_CONCRETE,
          &YELLOW_CONCRETE_POWDER,
          &YELLOW_GLAZED_TERRACOTTA,
          &YELLOW_SHULKER_BOX,
          &YELLOW_STAINED_GLASS,
          &YELLOW_STAINED_GLASS_PANE_TOP,
          &YELLOW_TERRACOTTA,
          &YELLOW_WOOL,
	             &LIGHT_GRAY_WOOL,
	             &LIGHTNING_ROD,
	             &LIGHTNING_ROD_ON,
	             &LILAC_BOTTOM,
	             &LILAC_TOP,
	             &LILY_OF_THE_VALLEY,
	             &LILY_PAD,
	             &LIME_CANDLE,
	             &LIME_CANDLE_LIT,
	             &LIME_CONCRETE,
	             &LIME_CONCRETE_POWDER,
	             &LIME_GLAZED_TERRACOTTA,
	             &LIME_SHULKER_BOX,
	             &LIME_STAINED_GLASS,
	             &LIME_STAINED_GLASS_PANE_TOP,
	             &LIME_TERRACOTTA,
	             &LIME_WOOL,
	             &LODESTONE_SIDE,
	             &LODESTONE_TOP,
	             &LOOM_BOTTOM,
	             &LOOM_FRONT,
	             &LOOM_SIDE,
	             &LOOM_TOP,
	             &MAGENTA_CANDLE,
	             &MAGENTA_CANDLE_LIT,
	             &MAGENTA_CONCRETE,
	             &MAGENTA_CONCRETE_POWDER,
	             &MAGENTA_GLAZED_TERRACOTTA,
	             &MAGENTA_SHULKER_BOX,
	             &MAGENTA_STAINED_GLASS,
	             &MAGENTA_STAINED_GLASS_PANE_TOP,
	             &MAGENTA_TERRACOTTA,
	             &MAGENTA_WOOL,
	             &MAGMA,
	             &MANGROVE_DOOR_BOTTOM,
	             &MANGROVE_DOOR_TOP,
	             &MANGROVE_LEAVES,
	             &MANGROVE_LOG,
	             &MANGROVE_LOG_TOP,
	             &MANGROVE_PLANKS,
	             &MANGROVE_PROPAGULE,
	             &MANGROVE_PROPAGULE_HANGING,
	             &MANGROVE_ROOTS_SIDE,
	             &MANGROVE_ROOTS_TOP,
	             &MANGROVE_TRAPDOOR,
	             &MEDIUM_AMETHYST_BUD,
	             &MELON_SIDE,
	             &MELON_STEM,
	             &MELON_TOP,
	             &MOSS_BLOCK,
	             &MOSSY_COBBLESTONE,
	             &MOSSY_STONE_BRICKS,
	             &MUD,
	             &MUD_BRICKS,
	             &MUDDY_MANGROVE_ROOTS_SIDE,
	             &MUDDY_MANGROVE_ROOTS_TOP,
	             &MUSHROOM_BLOCK_INSIDE,
	             &MUSHROOM_STEM,
	             &MYCELIUM_SIDE,
	             &MYCELIUM_TOP,
	             &NETHER_BRICKS,
	             &NETHER_GOLD_ORE,
	             &NETHER_PORTAL,
	             &NETHER_QUARTZ_ORE,
	             &NETHER_SPROUTS,
	             &NETHER_WART_BLOCK,
	             &NETHER_WART_STAGE0,
	             &NETHER_WART_STAGE1,
	             &NETHER_WART_STAGE2,
	             &NETHERITE_BLOCK,
	             &NETHERRACK,
	             &NOTE_BLOCK,
	             &OAK_DOOR_BOTTOM,
	             &OAK_DOOR_TOP,
	             &OAK_LEAVES,
	             &OAK_LOG,
	             &OAK_LOG_TOP,
	             &OAK_PLANKS,
	             &OAK_SAPLING,
	             &OAK_TRAPDOOR,
	             &OBSERVER_BACK,
	             &OBSERVER_BACK_ON,
	             &OBSERVER_FRONT,
	             &OBSERVER_SIDE,
	             &OBSERVER_TOP,
	             &OBSIDIAN,
	             &OCHRE_FROGLIGHT_SIDE,
	             &OCHRE_FROGLIGHT_TOP,
	             &ORANGE_CANDLE,
	             &ORANGE_CANDLE_LIT,
	             &ORANGE_CONCRETE,
	             &ORANGE_CONCRETE_POWDER,
	             &ORANGE_GLAZED_TERRACOTTA,
	             &ORANGE_SHULKER_BOX,
	             &ORANGE_STAINED_GLASS,
	             &ORANGE_STAINED_GLASS_PANE_TOP,
	             &ORANGE_TERRACOTTA,
	             &ORANGE_TULIP,
	             &ORANGE_WOOL,
	             &OXEYE_DAISY,
	             &OXIDIZED_COPPER,
	             &OXIDIZED_CUT_COPPER,
	             &PACKED_ICE,
	             &PACKED_MUD,
	             &PEARLESCENT_FROGLIGHT_SIDE,
	             &PEARLESCENT_FROGLIGHT_TOP,
	             &PEONY_BOTTOM,
	             &PEONY_TOP,
	             &PINK_CANDLE,
	             &PINK_CANDLE_LIT,
	             &PINK_CONCRETE,
	             &PINK_CONCRETE_POWDER,
	             &PINK_GLAZED_TERRACOTTA,
	             &PINK_SHULKER_BOX,
	             &PINK_STAINED_GLASS,
	             &PINK_STAINED_GLASS_PANE_TOP,
	             &PINK_TERRACOTTA,
	             &PINK_TULIP,
	             &PINK_WOOL,
	             &PISTON_BOTTOM,
	             &PISTON_INNER,
	             &PISTON_SIDE,
	             &PISTON_TOP,
	             &PISTON_TOP_STICKY,
	             &PODZOL_SIDE,
	             &PODZOL_TOP,
	             &POINTED_DRIPSTONE_DOWN_BASE,
	             &POINTED_DRIPSTONE_DOWN_FRUSTUM,
	             &POINTED_DRIPSTONE_DOWN_MIDDLE,
	             &POINTED_DRIPSTONE_DOWN_TIP,
	             &POINTED_DRIPSTONE_DOWN_TIP_MERGE,
	             &POINTED_DRIPSTONE_UP_BASE,
	             &POINTED_DRIPSTONE_UP_FRUSTUM,
	             &POINTED_DRIPSTONE_UP_MIDDLE,
	             &POINTED_DRIPSTONE_UP_TIP,
	             &POINTED_DRIPSTONE_UP_TIP_MERGE,
	             &POLISHED_ANDESITE,
	             &POLISHED_BASALT_SIDE,
	             &POLISHED_BASALT_TOP,
	             &POLISHED_BLACKSTONE,
	             &POLISHED_BLACKSTONE_BRICKS,
	             &POLISHED_DEEPSLATE,
	             &POLISHED_DIORITE,
	             &POLISHED_GRANITE,
	             &POPPY,
	             &POTATOES_STAGE0,
	             &POTATOES_STAGE1,
	             &POTATOES_STAGE2,
	             &POTATOES_STAGE3,
	             &POTTED_AZALEA_BUSH_PLANT,
	             &POTTED_AZALEA_BUSH_SIDE,
	             &POTTED_AZALEA_BUSH_TOP,
	             &POTTED_FLOWERING_AZALEA_BUSH_PLANT,
	             &POTTED_FLOWERING_AZALEA_BUSH_SIDE,
	             &POTTED_FLOWERING_AZALEA_BUSH_TOP,
	             &POWDER_SNOW,
	             &POWERED_RAIL,
	             &POWERED_RAIL_ON,
	             &PRISMARINE,
	             &PRISMARINE_BRICKS,
	             &PUMPKIN_SIDE,
	             &PUMPKIN_STEM,
	             &PUMPKIN_TOP,
	             &PURPLE_CANDLE,
	             &PURPLE_CANDLE_LIT,
	             &PURPLE_CONCRETE,
	             &PURPLE_CONCRETE_POWDER,
	             &PURPLE_GLAZED_TERRACOTTA,
	             &PURPLE_SHULKER_BOX,
	             &PURPLE_STAINED_GLASS,
	             &PURPLE_STAINED_GLASS_PANE_TOP,
	             &PURPLE_TERRACOTTA,
	             &PURPLE_WOOL,
	             &PURPUR_BLOCK,
	             &PURPUR_PILLAR,
	             &PURPUR_PILLAR_TOP,
	             &QUARTZ_BLOCK_BOTTOM,
	             &QUARTZ_BLOCK_SIDE,
	             &QUARTZ_BLOCK_TOP,
	             &QUARTZ_BRICKS,
	             &QUARTZ_PILLAR,
	             &QUARTZ_PILLAR_TOP,
	             &RAIL,
	             &RAIL_CORNER,
	             &RAW_COPPER_BLOCK,
	             &RAW_GOLD_BLOCK,
	             &RAW_IRON_BLOCK,
	             &RED_CANDLE,
	             &RED_CANDLE_LIT,
	             &RED_CONCRETE,
	             &RED_CONCRETE_POWDER,
	             &RED_GLAZED_TERRACOTTA,
	             &RED_MUSHROOM,
	             &RED_MUSHROOM_BLOCK,
	             &RED_NETHER_BRICKS,
	             &RED_SAND,
	             &RED_SANDSTONE,
	             &RED_SANDSTONE_BOTTOM,
	             &RED_SANDSTONE_TOP,
	             &RED_SHULKER_BOX,
	             &RED_STAINED_GLASS,
	             &RED_STAINED_GLASS_PANE_TOP,
	             &RED_TERRACOTTA,
	             &RED_TULIP,
	             &RED_WOOL,
	             &REDSTONE_BLOCK,
	             &REDSTONE_DUST_DOT,
	             &REDSTONE_DUST_LINE0,
	             &REDSTONE_DUST_LINE1,
	             &REDSTONE_DUST_OVERLAY,
	             &REDSTONE_LAMP,
	             &REDSTONE_LAMP_ON,
	             &REDSTONE_ORE,
	             &REDSTONE_TORCH,
	             &REDSTONE_TORCH_OFF,
	             &REINFORCED_DEEPSLATE_BOTTOM,
	             &REINFORCED_DEEPSLATE_SIDE,
	             &REINFORCED_DEEPSLATE_TOP,
	             &REPEATER,
	             &REPEATER_ON,
	             &REPEATING_COMMAND_BLOCK_BACK,
	             &REPEATING_COMMAND_BLOCK_CONDITIONAL,
	             &REPEATING_COMMAND_BLOCK_FRONT,
	             &REPEATING_COMMAND_BLOCK_SIDE,
	             &RESPAWN_ANCHOR_BOTTOM,
	             &RESPAWN_ANCHOR_SIDE0,
	             &RESPAWN_ANCHOR_SIDE1,
	             &RESPAWN_ANCHOR_SIDE2,
	             &RESPAWN_ANCHOR_SIDE3,
	             &RESPAWN_ANCHOR_SIDE4,
	             &RESPAWN_ANCHOR_TOP,
	             &RESPAWN_ANCHOR_TOP_OFF,
	             &ROOTED_DIRT,
	             &ROSE_BUSH_BOTTOM,
	             &ROSE_BUSH_TOP,
	             &SAND,
	             &SANDSTONE,
	             &SANDSTONE_BOTTOM,
	             &SANDSTONE_TOP,
	             &SCAFFOLDING_BOTTOM,
	             &SCAFFOLDING_SIDE,
	             &SCAFFOLDING_TOP,
	             &SCULK,
	             &SCULK_CATALYST_BOTTOM,
	             &SCULK_CATALYST_SIDE,
	             &SCULK_CATALYST_SIDE_BLOOM,
	             &SCULK_CATALYST_TOP,
	             &SCULK_CATALYST_TOP_BLOOM,
	             &SCULK_SENSOR_BOTTOM,
	             &SCULK_SENSOR_SIDE,
	             &SCULK_SENSOR_TENDRIL_ACTIVE,
	             &SCULK_SENSOR_TENDRIL_INACTIVE,
	             &SCULK_SENSOR_TOP,
	             &SCULK_SHRIEKER_BOTTOM,
	             &SCULK_SHRIEKER_CAN_SUMMON_INNER_TOP,
	             &SCULK_SHRIEKER_INNER_TOP,
	             &SCULK_SHRIEKER_SIDE,
	             &SCULK_SHRIEKER_TOP,
	             &SCULK_VEIN,
	             &SEA_LANTERN,
	             &SEA_PICKLE,
	             &SEAGRASS,
	             &SHROOMLIGHT,
	             &SHULKER_BOX,
	             &SLIME_BLOCK,
	             &SMALL_AMETHYST_BUD,
	             &SMALL_DRIPLEAF_SIDE,
	             &SMALL_DRIPLEAF_STEM_BOTTOM,
	             &SMALL_DRIPLEAF_STEM_TOP,
	             &SMALL_DRIPLEAF_TOP,
	             &SMITHING_TABLE_BOTTOM,
	             &SMITHING_TABLE_FRONT,
	             &SMITHING_TABLE_SIDE,
	             &SMITHING_TABLE_TOP,
	             &SMOKER_BOTTOM,
	             &SMOKER_FRONT,
	             &SMOKER_FRONT_ON,
	             &SMOKER_SIDE,
	             &SMOKER_TOP,
	             &SMOOTH_BASALT,
	             &SMOOTH_STONE,
	             &SMOOTH_STONE_SLAB_SIDE,
	             &SNOW,
	             &SOUL_CAMPFIRE_FIRE,
	             &SOUL_CAMPFIRE_LOG_LIT,
	             &SOUL_FIRE_0,
	             &SOUL_FIRE_1,
	             &SOUL_LANTERN,
	             &SOUL_SAND,
	             &SOUL_SOIL,
	             &SOUL_TORCH,
	             &SPAWNER,
	             &SPONGE,
	             &SPORE_BLOSSOM,
	             &SPORE_BLOSSOM_BASE,
	             &SPRUCE_DOOR_BOTTOM,
	             &SPRUCE_DOOR_TOP,
	             &SPRUCE_LEAVES,
	             &SPRUCE_LOG,
	             &SPRUCE_LOG_TOP,
	             &SPRUCE_PLANKS,
	             &SPRUCE_SAPLING,
	             &SPRUCE_TRAPDOOR,
	             &STONE,
	             &STONE_BRICKS,
	             &STONECUTTER_BOTTOM,
	             &STONECUTTER_SAW,
	             &STONECUTTER_SIDE,
	             &STONECUTTER_TOP,
	             &STRIPPED_ACACIA_LOG,
	             &STRIPPED_ACACIA_LOG_TOP,
	             &STRIPPED_BIRCH_LOG,
	             &STRIPPED_BIRCH_LOG_TOP,
	             &STRIPPED_CRIMSON_STEM,
	             &STRIPPED_CRIMSON_STEM_TOP,
	             &STRIPPED_DARK_OAK_LOG,
	             &STRIPPED_DARK_OAK_LOG_TOP,
	             &STRIPPED_JUNGLE_LOG,
	             &STRIPPED_JUNGLE_LOG_TOP,
	             &STRIPPED_MANGROVE_LOG,
	             &STRIPPED_MANGROVE_LOG_TOP,
	             &STRIPPED_OAK_LOG,
	             &STRIPPED_OAK_LOG_TOP,
	             &STRIPPED_SPRUCE_LOG,
	             &STRIPPED_SPRUCE_LOG_TOP,
	             &STRIPPED_WARPED_STEM,
	             &STRIPPED_WARPED_STEM_TOP,
	             &STRUCTURE_BLOCK,
	             &STRUCTURE_BLOCK_CORNER,
	             &STRUCTURE_BLOCK_DATA,
	             &STRUCTURE_BLOCK_LOAD,
	             &STRUCTURE_BLOCK_SAVE,
	             &SUGAR_CANE,
	             &SUNFLOWER_BACK,
	             &SUNFLOWER_BOTTOM,
	             &SUNFLOWER_FRONT,
	             &SUNFLOWER_TOP,
	             &SWEET_BERRY_BUSH_STAGE0,
	             &SWEET_BERRY_BUSH_STAGE1,
	             &SWEET_BERRY_BUSH_STAGE2,
	             &SWEET_BERRY_BUSH_STAGE3,
	             &TALL_GRASS_BOTTOM,
	             &TALL_GRASS_TOP,
	             &TALL_SEAGRASS_BOTTOM,
	             &TALL_SEAGRASS_TOP,
	             &TARGET_SIDE,
	             &TARGET_TOP,
	             &TERRACOTTA,
	             &TINTED_GLASS,
	             &TNT_BOTTOM,
	             &TNT_SIDE,
	             &TNT_TOP,
	             &TORCH,
	             &TRIPWIRE,
	             &TRIPWIRE_HOOK,
	             &TUBE_CORAL,
	             &TUBE_CORAL_BLOCK,
	             &TUBE_CORAL_FAN,
	             &TUFF,
	             &TURTLE_EGG,
	             &TURTLE_EGG_SLIGHTLY_CRACKED,
	             &TURTLE_EGG_VERY_CRACKED,
	             &TWISTING_VINES,
	             &TWISTING_VINES_PLANT,
	             &VERDANT_FROGLIGHT_SIDE,
	             &VERDANT_FROGLIGHT_TOP,
	             &VINE,
	             &WARPED_DOOR_BOTTOM,
	             &WARPED_DOOR_TOP,
	             &WARPED_FUNGUS,
	             &WARPED_NYLIUM,
	             &WARPED_NYLIUM_SIDE,
	             &WARPED_PLANKS,
	             &WARPED_ROOTS,
	             &WARPED_ROOTS_POT,
	             &WARPED_STEM,
	             &WARPED_STEM_TOP,
	             &WARPED_TRAPDOOR,
	             &WARPED_WART_BLOCK,
	             &WATER_FLOW,
	             &WATER_OVERLAY,
	             &WATER_STILL,
	             &WEATHERED_COPPER,
	             &WEATHERED_CUT_COPPER,
	             &WEEPING_VINES,
	             &WEEPING_VINES_PLANT,
	             &WET_SPONGE,
	             &WHEAT_STAGE0,
	             &WHEAT_STAGE1,
	             &WHEAT_STAGE2,
	             &WHEAT_STAGE3,
	             &WHEAT_STAGE4,
	             &WHEAT_STAGE5,
	             &WHEAT_STAGE6,
	             &WHEAT_STAGE7,
	             &WHITE_CANDLE,
	             &WHITE_CANDLE_LIT,
	             &WHITE_CONCRETE,
	             &WHITE_CONCRETE_POWDER,
	             &WHITE_GLAZED_TERRACOTTA,
	             &WHITE_SHULKER_BOX,
	             &WHITE_STAINED_GLASS,
	             &WHITE_STAINED_GLASS_PANE_TOP,
	             &WHITE_TERRACOTTA,
	             &WHITE_TULIP,
	             &WHITE_WOOL,
	             &WITHER_ROSE,
	             &YELLOW_CANDLE,
	             &YELLOW_CANDLE_LIT,
	             &YELLOW_CONCRETE,
	             &YELLOW_CONCRETE_POWDER,
	             &YELLOW_GLAZED_TERRACOTTA,
	             &YELLOW_SHULKER_BOX,
	             &YELLOW_STAINED_GLASS,
	             &YELLOW_STAINED_GLASS_PANE_TOP,
	             &YELLOW_TERRACOTTA,
	             &YELLOW_WOOL, }) {
}

BlockTextures::~BlockTextures() {}

/**
 * Loads all block textures from the 'blocks' directory.
 */
bool BlockTextures::load(const std::string &block_dir, int size, int blur, double water_opacity) {
    if (!fs::exists(block_dir) || !fs::is_directory(block_dir)) {
		LOG(ERROR) << "Directory '" << block_dir << "' with block textures does not exist.";
        return false;
    }

    // go through all textures and load them
	bool loaded_all = true;
    for (size_t i = 0; i < textures.size(); i++) {
        if (!textures[i]->load(block_dir, size, blur, water_opacity)) {
			LOG(WARNING) << "Unable to load block texture '" << textures[i]->getName() << ".png'.";
			loaded_all = false;
		}
    }
	if (!loaded_all)
		LOG(WARNING) << "Unable to load some block textures.";
    return true;
}

} // namespace renderer
} // namespace mapcrafter
